const state={catalog:[],filtered:[],pageSize:24,page:1,route:'home',gameId:null,tab:'about',filters:{query:'',genres:[],platforms:[],yearFrom:'',yearTo:'',criticMin:'',userMin:'',sort:'popular'},profile:JSON.parse(localStorage.getItem('igropoisk-profile')||'{"want":[],"playing":[],"completed":[],"ratings":{}}')};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const saveProfile=()=>localStorage.setItem('igropoisk-profile',JSON.stringify(state.profile));
const fmt=n=>Number.isFinite(+n)?(+n).toFixed(1).replace('.',','):'—';
async function loadCatalog(){try{const r=await fetch('./data/catalog.json',{cache:'no-store'});const d=await r.json();state.catalog=Array.isArray(d)?d:(d.games||[])}catch(e){state.catalog=[]}applyFilters();render();}
function normalize(g){return{...g,id:String(g.id||g.appid||g.slug||g.name),title:g.title||g.name||'Без названия',year:+(g.year||String(g.release_date||'').match(/\d{4}/)?.[0]||0),genres:g.genres||String(g.genre||'').split(',').map(x=>x.trim()).filter(Boolean),platforms:g.platforms||[],criticRating:+(g.criticRating||g.critics||0),userRating:+(g.userRating||g.users||g.score||0),poster:g.poster||g.cover||g.images?.poster||`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.appid}/library_600x900.jpg`,hero:g.hero||g.background||g.images?.hero||`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.appid}/library_hero.jpg`}}
function applyFilters(){const f=state.filters;let a=state.catalog.map(normalize).filter(g=>{const q=(g.title+' '+g.genres.join(' ')+' '+(g.developer||'')).toLowerCase();if(f.query&&!q.includes(f.query.toLowerCase()))return false;if(f.genres.length&&!f.genres.every(x=>g.genres.includes(x)))return false;if(f.platforms.length&&!f.platforms.some(x=>g.platforms.includes(x)))return false;if(f.yearFrom&&g.year<+f.yearFrom)return false;if(f.yearTo&&g.year>+f.yearTo)return false;if(f.criticMin&&g.criticRating<+f.criticMin)return false;if(f.userMin&&g.userRating<+f.userMin)return false;return true});a.sort((x,y)=>f.sort==='critic'?y.criticRating-x.criticRating:f.sort==='user'?y.userRating-x.userRating:f.sort==='year'?y.year-x.year:x.title.localeCompare(y.title,'ru'));state.filtered=a;state.page=1;}
function setRoute(route,id=null,tab='about'){state.route=route;state.gameId=id;state.tab=tab;location.hash=route==='game'?`game/${id}/${tab}`:route;render();}
function readHash(){const p=location.hash.slice(1).split('/');state.route=p[0]||'home';state.gameId=p[1]||null;state.tab=p[2]||'about';render();}
function gameCard(g){return `<article class="game-card" data-open-game="${g.id}"><img src="${g.poster}" alt=""><div class="game-card__body"><h3>${g.title}</h3><p>${g.genres.slice(0,2).join(' · ')}${g.year?' · '+g.year:''}</p><div class="ratings"><span>Критики <b>${fmt(g.criticRating)}</b></span><span>Игроки <b>${fmt(g.userRating)}</b></span></div></div></article>`}
function renderHome(){const top=[...state.catalog].map(normalize).sort((a,b)=>b.criticRating-a.criticRating).slice(0,10);return `<section class="hero"><div><p class="eyebrow">Игропоиск</p><h1>Найди следующую игру</h1><p>Каталог, рейтинги, материалы и личная коллекция.</p><button data-nav="catalog">Открыть каталог</button></div></section><section class="section"><div class="section-head"><h2>Лучшие игры</h2><button data-nav="catalog">Все игры</button></div><div class="grid">${top.map(gameCard).join('')}</div></section>`}
function renderFilters(){return `<aside class="filters"><h2>Фильтры</h2><label>Поиск<input id="filter-query" value="${state.filters.query}" placeholder="Название или студия"></label><label>Год от<input id="year-from" type="number" value="${state.filters.yearFrom}"></label><label>Год до<input id="year-to" type="number" value="${state.filters.yearTo}"></label><label>Рейтинг критиков<select id="critic-min"><option value="">Любой</option>${[7,8,9].map(x=>`<option ${state.filters.criticMin==x?'selected':''}>${x}</option>`).join('')}</select></label><label>Рейтинг игроков<select id="user-min"><option value="">Любой</option>${[7,8,9].map(x=>`<option ${state.filters.userMin==x?'selected':''}>${x}</option>`).join('')}</select></label><label>Сортировка<select id="sort"><option value="popular">По названию</option><option value="critic">По критикам</option><option value="user">По игрокам</option><option value="year">По дате</option></select></label><button id="apply-filters">Применить</button><button class="secondary" id="reset-filters">Сбросить</button></aside>`}
function renderCatalog(){const shown=state.filtered.slice(0,state.page*state.pageSize);return `<div class="catalog-layout">${renderFilters()}<main><div class="section-head"><div><h1>Каталог игр</h1><p>${state.filtered.length} результатов</p></div></div><div class="grid">${shown.map(gameCard).join('')}</div>${shown.length<state.filtered.length?'<button id="load-more">Показать ещё</button>':''}</main></div>`}
function getGame(){return state.catalog.map(normalize).find(g=>g.id===String(state.gameId))||normalize(state.catalog[0]||{})}
const tabLabels={about:'Всё об игре',articles:'Статьи',reviews:'Обзоры',userreviews:'Рецензии',guides:'Гайды',tips:'Советы',news:'Новости'};
function renderMaterialList(items,type){if(!items?.length)return `<div class="empty">Материалы раздела «${tabLabels[type]}» появятся после очередного обновления источников.</div>`;return items.map(x=>`<article class="material"><h3>${x.title}</h3><p>${x.summary||''}</p><a href="${x.url}" target="_blank" rel="noopener">${x.source||'Источник'} ↗</a></article>`).join('')}
function renderGame(){const g=getGame();const status=['want','playing','completed'].find(k=>state.profile[k].includes(g.id));const tabs=Object.entries(tabLabels).map(([k,v])=>`<button class="${state.tab===k?'active':''}" data-game-tab="${k}">${v}</button>`).join('');let body='';if(state.tab==='about')body=`<div class="game-about"><main><h2>Описание</h2><p>${g.description||g.desc||'Описание обновляется.'}</p><h2>Сюжет</h2><p>${g.story||'Сюжетное описание обновляется.'}</p><h2>Особенности</h2><ul>${(g.features||g.tags||[]).map(x=>`<li>${x}</li>`).join('')||'<li>Особенности обновляются.</li>'}</ul><h2>Скриншоты</h2><div class="screens">${(g.screenshots||[]).slice(0,8).map(x=>`<img src="${x.url||x}" alt="">`).join('')}</div></main><aside><dl><dt>Дата выхода</dt><dd>${g.release_date||g.release||'—'}</dd><dt>Жанры</dt><dd>${g.genres.join(', ')||'—'}</dd><dt>Платформы</dt><dd>${g.platforms.join?.(', ')||g.platforms||'—'}</dd><dt>Разработчик</dt><dd>${g.developer||'—'}</dd><dt>Издатель</dt><dd>${g.publisher||'—'}</dd></dl></aside></div>`;else body=renderMaterialList(g.materials?.[state.tab]||g[state.tab],state.tab);return `<section class="game-hero" style="background-image:linear-gradient(90deg,rgba(0,0,0,.92),rgba(0,0,0,.25)),url('${g.hero}')"><div><p>${g.genres.join(' · ')}</p><h1>${g.title}</h1><div class="hero-ratings"><span>Игропоиск <b>${fmt(g.rating||((g.criticRating+g.userRating)/2))}</b></span><span>Критики <b>${fmt(g.criticRating)}</b></span><span>Игроки <b>${fmt(g.userRating)}</b></span></div><div class="status-actions"><button data-status="want" class="${status==='want'?'active':''}">Хочу сыграть</button><button data-status="playing" class="${status==='playing'?'active':''}">Играю</button><button data-status="completed" class="${status==='completed'?'active':''}">Пройдено</button></div></div></section><nav class="game-tabs">${tabs}</nav><section class="game-content">${body}</section>`}
function renderProfile(){return `<section class="section"><h1>Моя коллекция</h1>${['want','playing','completed'].map(k=>`<div class="profile-block"><h2>${{want:'Хочу сыграть',playing:'Играю',completed:'Пройдено'}[k]}</h2><div class="grid">${state.profile[k].map(id=>state.catalog.map(normalize).find(g=>g.id===id)).filter(Boolean).map(gameCard).join('')||'<div class="empty">Пока пусто</div>'}</div></div>`).join('')}</section>`}
function render(){const app=$('#app');if(!app)return;app.innerHTML=state.route==='catalog'?renderCatalog():state.route==='game'?renderGame():state.route==='profile'?renderProfile():renderHome();bind();}
function bind(){$$('[data-nav]').forEach(x=>x.onclick=()=>setRoute(x.dataset.nav));$$('[data-open-game]').forEach(x=>x.onclick=()=>setRoute('game',x.dataset.openGame));$$('[data-game-tab]').forEach(x=>x.onclick=()=>setRoute('game',state.gameId,x.dataset.gameTab));$$('[data-status]').forEach(x=>x.onclick=()=>{const id=getGame().id;['want','playing','completed'].forEach(k=>state.profile[k]=state.profile[k].filter(v=>v!==id));state.profile[x.dataset.status].push(id);saveProfile();render()});$('#apply-filters')?.addEventListener('click',()=>{state.filters.query=$('#filter-query').value;state.filters.yearFrom=$('#year-from').value;state.filters.yearTo=$('#year-to').value;state.filters.criticMin=$('#critic-min').value;state.filters.userMin=$('#user-min').value;state.filters.sort=$('#sort').value;applyFilters();render()});$('#reset-filters')?.addEventListener('click',()=>{state.filters={query:'',genres:[],platforms:[],yearFrom:'',yearTo:'',criticMin:'',userMin:'',sort:'popular'};applyFilters();render()});$('#load-more')?.addEventListener('click',()=>{state.page++;render()})}
window.addEventListener('hashchange',readHash);document.addEventListener('DOMContentLoaded',()=>{readHash();loadCatalog()});