const S={games:[],route:'home',id:null,tab:'about'};const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const fmt=n=>Number.isFinite(+n)?(+n).toFixed(1).replace('.',','):'—';
function hash(){const p=location.hash.slice(1).split('/');S.route=p[0]||'home';S.id=p[1]||null;S.tab=p[2]||'about';render()}
function card(g){return `<article class="game-card" data-game="${g.id}"><div class="poster"><img src="${g.poster}" alt="${esc(g.title)}"><b>${fmt(g.rating)}</b></div><h3>${esc(g.title)}</h3><p>${esc(g.genres.join(' · '))} · ${g.year}</p></article>`}
function home(){const f=S.games[0];return `<section class="hero" style="background-image:linear-gradient(90deg,rgba(0,0,0,.92),rgba(0,0,0,.2)),url('${f.hero}')"><div><span>Игра дня</span><h1>${esc(f.title)}</h1><p>${esc(f.description)}</p><button data-game="${f.id}">Всё об игре</button></div></section><section class="section"><h2>Популярные игры</h2><div class="grid">${S.games.map(card).join('')}</div></section>`}
function catalog(){return `<section class="section"><div class="catalog-head"><div><h1>Каталог игр</h1><p>${S.games.length} игр</p></div><input id="q" placeholder="Поиск по названию, жанру, студии"></div><div class="grid" id="catalog-grid">${S.games.map(card).join('')}</div></section>`}
function tabs(g){const t=[['about','Всё об игре'],['screens','Медиа'],['articles','Статьи'],['reviews','Обзоры'],['guides','Гайды'],['tips','Советы'],['news','Новости']];return `<nav class="tabs">${t.map(([k,v])=>`<button class="${S.tab===k?'active':''}" data-tab="${k}">${v}</button>`).join('')}</nav>`}
function materialList(items,label){return items?.length?`<div class="materials">${items.map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.summary||'')}</p><a href="${x.url}" target="_blank" rel="noopener">${esc(x.source||'Источник')} ↗</a></article>`).join('')}</div>`:`<div class="empty">В разделе «${label}» пока нет материалов.</div>`}
function game(){const g=S.games.find(x=>x.id===S.id)||S.games[0];let body='';if(S.tab==='about')body=`<div class="game-layout"><main><h2>Описание</h2><p>${esc(g.description)}</p><h2>Сюжет</h2><p>${esc(g.story)}</p><h2>Особенности</h2><div class="features">${g.features.map(x=>`<div>${esc(x)}</div>`).join('')}</div><h2>Скриншоты</h2><div class="screens">${g.screenshots.map(x=>`<img src="${x}" alt="">`).join('')}</div></main><aside><h3>Информация</h3><dl><dt>Дата выхода</dt><dd>${esc(g.release)}</dd><dt>Жанры</dt><dd>${esc(g.genres.join(', '))}</dd><dt>Платформы</dt><dd>${esc(g.platforms.join(', '))}</dd><dt>Разработчик</dt><dd>${esc(g.developer)}</dd><dt>Издатель</dt><dd>${esc(g.publisher)}</dd></dl></aside></div>`;else if(S.tab==='screens')body=`<div class="screens large">${g.screenshots.map(x=>`<img src="${x}" alt="">`).join('')}</div>`;else body=materialList(g.materials?.[S.tab],S.tab);return `<section class="game-hero" style="background-image:linear-gradient(90deg,rgba(0,0,0,.94),rgba(0,0,0,.2)),url('${g.hero}')"><div><span>${esc(g.genres.join(' · '))}</span><h1>${esc(g.title)}</h1><p>${esc(g.description)}</p><div class="scores"><b>Игропоиск ${fmt(g.rating)}</b><b>Критики ${fmt(g.critics)}</b><b>Игроки ${fmt(g.users)}</b></div></div></section>${tabs(g)}<section class="section">${body}</section>`}
function render(){const app=$('#app');if(!S.games.length){app.innerHTML='<div class="empty">Загрузка…</div>';return}app.innerHTML=S.route==='catalog'?catalog():S.route==='game'?game():home();bind()}
function bind(){document.querySelectorAll('[data-game]').forEach(x=>x.onclick=()=>location.hash=`game/${x.dataset.game}/about`);document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>location.hash=`game/${S.id}/${x.dataset.tab}`);const q=$('#q');if(q)q.oninput=()=>{const v=q.value.toLowerCase();$('#catalog-grid').innerHTML=S.games.filter(g=>(g.title+' '+g.genres.join(' ')+' '+g.developer).toLowerCase().includes(v)).map(card).join('');bind()}}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)location.hash=n.dataset.nav});window.addEventListener('hashchange',hash);fetch('./data/catalog.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{S.games=d.games||d;hash()}).catch(()=>{$('#app').innerHTML='<div class="empty">Не удалось загрузить каталог.</div>'});