const S={games:[],route:'home',id:null,tab:'about',timer:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>Number.isFinite(+n)&&+n>0?(+n).toFixed(1).replace('.',','):'';
const slug=s=>String(s||'game').toLowerCase().replace(/[^a-z0-9а-яё]+/gi,'-').replace(/^-|-$/g,'');
function route(){const p=location.hash.slice(1).split('/');S.route=p[0]||'home';S.id=p[1]||null;S.tab=p[2]||'about';render()}
function card(g){return `<article class="game-card" data-game="${g.id}"><div class="poster"><img loading="lazy" src="${g.poster}" alt="${esc(g.title)}" onerror="this.src='${g.header}'">${g.rating?`<b>${fmt(g.rating)}</b>`:''}</div><h3>${esc(g.title)}</h3><p>${esc(g.genres.slice(0,3).join(' · '))}${g.year?' · '+g.year:''}</p></article>`}
function slides(g){return [...new Set([g.hero,g.header,...(g.screenshots||[]).slice(0,6)].filter(Boolean))]}
function hero(g,isHome=false){const a=slides(g);const players=g.userVotes>0&&g.users?`<span>Игроки <strong>${fmt(g.users)}</strong></span>`:'';return `<section class="${isHome?'hero':'game-hero'} hero-slider" data-slides='${esc(JSON.stringify(a))}'><div class="hero-bg active" style="background-image:linear-gradient(90deg,rgba(0,0,0,.94),rgba(0,0,0,.22)),url('${a[0]||''}')"></div><div class="hero-content"><span>${isHome?'Игра дня':esc(g.genres.slice(0,4).join(' · '))}</span><h1>${esc(g.title)}</h1><p>${esc(g.description)}</p><div class="inline-ratings"><span>Игропоиск <strong>${fmt(g.rating)||'—'}</strong></span>${players}</div>${isHome?`<button data-game="${g.id}">Всё об игре</button>`:''}</div><div class="hero-dots">${a.map((_,i)=>`<button class="${i?'':'active'}" data-slide="${i}"></button>`).join('')}</div></section>`}
function home(){const f=S.games[Math.floor(Date.now()/86400000)%S.games.length];const latest=[...S.games].sort((a,b)=>(b.year||0)-(a.year||0)).slice(0,10);return `${hero(f,true)}<section class="section"><h2>Популярные игры</h2><div class="grid">${S.games.slice(0,20).map(card).join('')}</div></section><section class="section"><h2>Новые релизы</h2><div class="grid">${latest.map(card).join('')}</div></section>`}
function catalog(){return `<section class="section"><div class="catalog-head"><div><h1>Каталог игр</h1><p>${S.games.length} игр</p></div><input id="q" placeholder="Поиск по названию, жанру, студии"></div><div class="grid" id="catalog-grid">${S.games.map(card).join('')}</div></section>`}
function tabs(){return `<nav class="tabs">${[['about','Всё об игре'],['screens','Медиа'],['articles','Статьи'],['reviews','Обзоры'],['guides','Гайды'],['tips','Советы'],['news','Новости']].map(([k,v])=>`<button class="${S.tab===k?'active':''}" data-tab="${k}">${v}</button>`).join('')}</nav>`}
function sourceList(g){const q=encodeURIComponent(g.title);return [['Официальный сайт игры',g.website],['Steam',g.appid?`https://store.steampowered.com/app/${g.appid}/`:''],['IGDB','https://www.igdb.com/'],['RAWG','https://rawg.io/'],['Metacritic','https://www.metacritic.com/'],['OpenCritic','https://opencritic.com/'],['IGN',`https://www.ign.com/search?q=${q}`],['GameSpot',`https://www.gamespot.com/search/?q=${q}`],['PC Gamer',`https://www.pcgamer.com/search/?searchTerm=${q}`],['Eurogamer',`https://www.eurogamer.net/search?keyword=${q}`],['Rock Paper Shotgun',`https://www.rockpapershotgun.com/search?q=${q}`],['Игромания',`https://www.igromania.ru/search/?q=${q}`],['StopGame',`https://stopgame.ru/search?s=${q}`],['GameMAG',`https://gamemag.ru/search?q=${q}`]].filter(x=>x[1]).slice(0,15)}
function sources(g){const a=sourceList(g);return `<details class="source-evidence"><summary>Источники страницы (${a.length})</summary><p>Редакционный текст Игропоиска должен строиться после анализа 10–20 источников. Официальные сайты игры и издателя имеют наивысший приоритет.</p><div>${a.map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener">${esc(n)} ↗</a>`).join('')}</div></details>`}
function external(g,type){const q=encodeURIComponent(g.title+' '+type);return [['IGN',`https://www.ign.com/search?q=${q}`],['GameSpot',`https://www.gamespot.com/search/?q=${q}`],['PC Gamer',`https://www.pcgamer.com/search/?searchTerm=${q}`],['Eurogamer',`https://www.eurogamer.net/search?keyword=${q}`],['Игромания',`https://www.igromania.ru/search/?q=${q}`],['StopGame',`https://stopgame.ru/search?s=${q}`],['GameMAG',`https://gamemag.ru/search?q=${q}`]].map(([source,url])=>({source,url,title:`${g.title}: ${type} — ${source}`,summary:'Материал внешнего издания. Полный текст открывается у первоисточника.'}))}
function materials(g,type){const items=external(g,type);return `<div class="editorial-note"><b>Правило:</b> собственная статья Игропоиска публикуется только после анализа 10–20 источников и содержит раскрываемый список использованных источников.</div><div class="materials">${items.map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><a href="${x.url}" target="_blank" rel="noopener">${esc(x.source)} ↗</a></article>`).join('')}</div>${sources(g)}`}
function media(g){const videos=(g.movies||[]).filter(v=>v.webm||v.mp4||v.url);return `<h2>Скриншоты</h2><div class="screens large">${(g.screenshots||[]).map(x=>`<img loading="lazy" src="${x}" alt="Скриншот ${esc(g.title)}">`).join('')}</div><h2>Видео</h2>${videos.length?`<div class="videos">${videos.map(v=>`<video controls preload="metadata" poster="${v.thumbnail||g.header}"><source src="${v.webm||v.mp4||v.url}"></video>`).join('')}</div>`:`<div class="empty">Официальное видео пока не добавлено.</div>`}`}
function game(){const g=S.games.find(x=>x.id===S.id)||S.games[0];let body;if(S.tab==='about')body=`<div class="game-layout"><main><h2>Описание</h2><p>${esc(g.description)}</p><h2>Об игре</h2><p>${esc(g.about||g.description)}</p><h2>Особенности</h2><div class="features">${g.features.map(x=>`<div>${esc(x)}</div>`).join('')}</div><h2>Скриншоты</h2><div class="screens">${g.screenshots.slice(0,8).map(x=>`<img loading="lazy" src="${x}" alt="Скриншот ${esc(g.title)}">`).join('')}</div>${sources(g)}</main><aside><h3>Информация</h3><dl><dt>Дата выхода</dt><dd>${esc(g.release)}</dd><dt>Жанры</dt><dd>${esc(g.genres.join(', '))}</dd><dt>Платформы</dt><dd>${esc(g.platforms.join(', '))}</dd><dt>Разработчик</dt><dd>${esc(g.developer)}</dd><dt>Издатель</dt><dd>${esc(g.publisher)}</dd></dl></aside></div>`;else if(S.tab==='screens')body=media(g);else body=materials(g,{articles:'статьи',reviews:'обзоры',guides:'гайды',tips:'советы',news:'новости'}[S.tab]||S.tab);return `${hero(g)}${tabs()}<section class="section">${body}</section>`}
function initSlider(){clearInterval(S.timer);const root=$('.hero-slider');if(!root)return;let a=[];try{a=JSON.parse(root.dataset.slides||'[]')}catch{}if(a.length<2)return;let i=0;const go=n=>{i=(n+a.length)%a.length;const bg=root.querySelector('.hero-bg');bg.classList.remove('active');setTimeout(()=>{bg.style.backgroundImage=`linear-gradient(90deg,rgba(0,0,0,.94),rgba(0,0,0,.22)),url('${a[i]}')`;bg.classList.add('active')},180);root.querySelectorAll('[data-slide]').forEach((d,j)=>d.classList.toggle('active',j===i))};root.querySelectorAll('[data-slide]').forEach(d=>d.onclick=()=>go(+d.dataset.slide));S.timer=setInterval(()=>go(i+1),5500)}
function render(){const app=$('#app');if(!S.games.length){app.innerHTML='<div class="empty">Загрузка каталога…</div>';return}app.innerHTML=S.route==='catalog'?catalog():S.route==='game'?game():home();bind();initSlider()}
function bind(){document.querySelectorAll('[data-game]').forEach(x=>x.onclick=()=>location.hash=`game/${x.dataset.game}/about`);document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>location.hash=`game/${S.id}/${x.dataset.tab}`);const q=$('#q');if(q)q.oninput=()=>{const v=q.value.toLowerCase();$('#catalog-grid').innerHTML=S.games.filter(g=>(g.title+' '+g.genres.join(' ')+' '+g.developer).toLowerCase().includes(v)).map(card).join('');bind()}}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)location.hash=n.dataset.nav});window.addEventListener('hashchange',route);
function rowToGame(r){const x=r.row||r,appid=String(x.appID||x.appid||''),release=String(x.release_date||''),year=(release.match(/\b(19|20)\d{2}\b/)||[])[0],pos=Number(x.positive||0),neg=Number(x.negative||0),steam=pos+neg?Math.round(pos/(pos+neg)*100)/10:null,meta=Number(x.metacritic_score||0)?Number(x.metacritic_score)/10:null,rating=meta&&steam?Math.round((meta*.65+steam*.35)*10)/10:(meta||steam),shots=(Array.isArray(x.screenshots)?x.screenshots:[]).filter(Boolean),movies=(Array.isArray(x.movies)?x.movies:[]).map(v=>typeof v==='string'?{url:v}:v);return {id:slug(x.name)+'-'+appid,appid,title:x.name||'Без названия',year:Number(year)||null,release,genres:Array.isArray(x.genres)?x.genres:[],rating,users:null,userVotes:0,developer:(x.developers||[]).join(', ')||'—',publisher:(x.publishers||[]).join(', ')||'—',platforms:[x.windows&&'Windows',x.mac&&'macOS',x.linux&&'Linux'].filter(Boolean),description:x.short_description||x.detailed_description||'',about:String(x.detailed_description||x.short_description||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim(),features:[...new Set([...(x.tags||[]).slice(0,6),...(x.categories||[]).slice(0,4)])].slice(0,8),poster:`https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/library_600x900.jpg`,header:x.header_image||`https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/header.jpg`,hero:`https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/library_hero.jpg`,screenshots:shots.length?shots:[x.header_image].filter(Boolean),movies,website:x.website||''}}
async function mass(){const base='https://datasets-server.huggingface.co/filter',params={dataset:'zjgeritz/steam-games-dataset',config:'default',split:'train',where:'"recommendations">5000 AND "short_description"<>\'\'',orderby:'"recommendations" DESC',length:'100'},get=async offset=>{const u=new URL(base);Object.entries({...params,offset:String(offset)}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);if(!r.ok)throw Error(r.status);return r.json()},[a,b]=await Promise.all([get(0),get(100)]);return [...(a.rows||[]),...(b.rows||[])].map(rowToGame).filter(g=>g.appid&&g.description&&g.screenshots.length)}
(async()=>{try{const x=await mass();if(x.length>=100){S.games=x.slice(0,200);route();return}}catch(e){console.warn('Mass catalog unavailable',e)}try{const r=await fetch('./data/catalog.json',{cache:'no-store'}),d=await r.json();S.games=d.games||d;route()}catch{$('#app').innerHTML='<div class="empty">Не удалось загрузить каталог.</div>'}})();