import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('Notes visual-only placeholder and list marker stay out of selection', () {
    final source = File(
      'lib/features/notes/widgets/note_editor_block_widgets.dart',
    ).readAsStringSync();

    expect(
      source,
      contains(
        'text.isEmpty\n              ? SelectionContainer.disabled(child: renderedText)\n              : renderedText',
      ),
      reason:
          'Empty-block hints such as "Write something" must remain visual-only and never enter SelectionArea clipboard text.',
    );
    expect(
      source,
      contains('SelectionContainer.disabled(child: marker)'),
      reason:
          'Rendered list markers are regenerated by structured clipboard export and must not contaminate SelectionArea text.',
    );
  });
}
