from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

compat_path = ROOT / 'lib/data/paths/compatibility/path_governance_service.dart'
compat = compat_path.read_text(encoding='utf-8')
old = '''/// Startup baseline only: ensure recurring routine and migrate old broken\n/// generated rows. It does not schedule new project work.\nFuture<void> ensurePlannerBaselineV7() async {\n  final db = DatabaseService.instance;\n  await db.refreshCategoryRulesFromServer();\n  await ensureDailyRoutineV6();\n  await _removeSupersededWeekRoutinesV5();\n  await _migrateLegacyApprovalDuplicatesV7();\n}\n'''
new = '''/// Compatibility-only cleanup for planner rows generated by the old Paths\n/// governance pipeline. This never schedules new project work.\nFuture<void> runLegacyPathPlannerCleanupV7() async {\n  await _removeSupersededWeekRoutinesV5();\n  await _migrateLegacyApprovalDuplicatesV7();\n}\n\n/// Compatibility entrypoint kept for older callers. New startup callers use\n/// `PlannerStartupService` from `data/plans`.\nFuture<void> ensurePlannerBaselineV7() async {\n  final db = DatabaseService.instance;\n  await db.refreshCategoryRulesFromServer();\n  await ensureDailyRoutineV6();\n  await runLegacyPathPlannerCleanupV7();\n}\n'''
if old not in compat:
    raise RuntimeError('planner baseline block not found')
compat_path.write_text(compat.replace(old, new, 1), encoding='utf-8')

app_path = ROOT / 'lib/app/shell/app_shell.dart'
app = app_path.read_text(encoding='utf-8')
old_import = "import 'package:counter/data/paths/compatibility/path_governance_service.dart';\n"
new_import = "import 'package:counter/data/plans/planner_startup_service.dart';\n"
if old_import not in app:
    raise RuntimeError('shell Paths compatibility import not found')
app_path.write_text(app.replace(old_import, new_import, 1), encoding='utf-8')

lifecycle_path = ROOT / 'lib/app/shell/shared/shell_lifecycle.dart'
lifecycle = lifecycle_path.read_text(encoding='utf-8')
old_call = '''        try {\n          await ensurePlannerBaselineV7();\n        } catch (e) {\n          debugPrint('[PLANNER_BASELINE_V7] ensure failed: $e');\n        }\n'''
new_call = '''        try {\n          await PlannerStartupService.instance.ensureBaseline();\n        } catch (e) {\n          debugPrint('[PLANNER_STARTUP] ensure failed: $e');\n        }\n'''
if old_call not in lifecycle:
    raise RuntimeError('shell planner baseline call not found')
lifecycle_path.write_text(lifecycle.replace(old_call, new_call, 1), encoding='utf-8')

structure_path = ROOT / 'docs/APP_STRUCTURE.md'
doc = structure_path.read_text(encoding='utf-8')
lines = doc.splitlines()
startup_row = '| `plans/planner_startup_service.dart` | Planning-owned startup baseline: category refresh, daily routine ensure, and isolated historical Path-generated-row cleanup |'
if startup_row not in lines:
    for index, line in enumerate(lines):
        if line.startswith('| `plans/daily_routine_service.dart` |'):
            lines.insert(index + 1, startup_row)
            break
    else:
        raise RuntimeError('daily_routine_service structure row not found')
for index, line in enumerate(lines):
    if line.startswith('| `paths/compatibility/path_governance_service.dart` |'):
        lines[index] = '| `paths/compatibility/path_governance_service.dart` | Compatibility-era project-specific Paths governance/migrations; exposes a cleanup hook but is not a shell startup dependency |'
        break
else:
    raise RuntimeError('path governance structure row not found')
for index, line in enumerate(lines):
    if line.startswith('| `app/shell/shared/shell_lifecycle.dart` |'):
        lines[index] = '| `app/shell/shared/shell_lifecycle.dart` | Shell startup/dispose wiring; delegates Planning baseline to `PlannerStartupService` and does not import Paths compatibility *(part)* |'
        break
else:
    raise RuntimeError('shell lifecycle structure row not found')
structure_path.write_text('\n'.join(lines) + ('\n' if doc.endswith('\n') else ''), encoding='utf-8')

changelog_path = ROOT / 'CHANGELOG.md'
changelog = changelog_path.read_text(encoding='utf-8')
entry = '''## 2026-08-18 — Planning startup ownership [engineering]\n\n- Added `PlannerStartupService` under `data/plans`; shell startup now delegates Planning baseline work there.\n- Shell no longer imports Paths compatibility governance directly.\n- Historical Path-generated-row cleanup is exposed as an explicit compatibility hook; daily routine and migration behavior are preserved and project governance is still not auto-scheduled at startup.\n\n'''
if not changelog.startswith('## 2026-08-18 — Planning startup ownership [engineering]'):
    changelog_path.write_text(entry + changelog, encoding='utf-8')

test_path = ROOT / 'test/daily_routine_contract_test.dart'
test_path.write_text("""import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('daily routine uses one deterministic recurring series per anchor', () {
    final source = File(
      'lib/data/plans/daily_routine_service.dart',
    ).readAsStringSync();

    expect(source, contains('_dailyRoutineMarkerV6'));
    expect(source, contains('_routineSeriesPlanIdV7'));
    expect(source, contains('FREQ=DAILY'));
    expect(source, contains('clientPlanId: deterministicPlanId'));
  });

  test(
    'path actions use unique deterministic plan ids and migration cleanup stays isolated',
    () {
      final source = File(
        'lib/data/paths/compatibility/path_governance_service.dart',
      ).readAsStringSync();

      expect(source, contains('_pathActionBusinessIdV7'));
      expect(source, contains('clientPlanId: planBusinessId'));
      expect(source, contains('_migrateLegacyApprovalDuplicatesV7'));
      expect(source, contains('_plannerBaselineMigrationV7'));
    },
  );

  test(
    'ordinary shell startup delegates Planning baseline without scheduling project actions',
    () {
      final lifecycle = File(
        'lib/app/shell/shared/shell_lifecycle.dart',
      ).readAsStringSync();
      final shell = File('lib/app/shell/app_shell.dart').readAsStringSync();
      final startup = File(
        'lib/data/plans/planner_startup_service.dart',
      ).readAsStringSync();
      final governance = File(
        'lib/data/paths/compatibility/path_governance_service.dart',
      ).readAsStringSync();

      expect(shell, contains('initializeShellLifecycle();'));
      expect(
        shell,
        contains(\"package:counter/data/plans/planner_startup_service.dart\"),
      );
      expect(
        shell,
        isNot(
          contains(
            \"package:counter/data/paths/compatibility/path_governance_service.dart\",
          ),
        ),
      );
      expect(
        lifecycle,
        contains('await PlannerStartupService.instance.ensureBaseline();'),
      );
      expect(lifecycle, isNot(contains('planCurrentWeekFromPathsV4')));

      expect(startup, contains('await ensureDailyRoutineV6();'));
      expect(startup, contains('await runLegacyPathPlannerCleanupV7();'));
      expect(startup, isNot(contains('planCurrentWeekFromPathsV4')));

      expect(
        governance,
        contains('Future<void> runLegacyPathPlannerCleanupV7()'),
      );
      final start = governance.indexOf(
        'Future<void> runLegacyPathPlannerCleanupV7()',
      );
      final body = governance.substring(
        start,
        governance.indexOf('\\n}', start) + 2,
      );
      expect(body, contains('_migrateLegacyApprovalDuplicatesV7'));
      expect(body, isNot(contains('planCurrentWeekFromPathsV4')));
    },
  );
}
""", encoding='utf-8')
