"""Concrete EN+RU guides for docs/*.md — no generic Markdown wrappers."""

from __future__ import annotations

from pathlib import PurePosixPath

from structure_ru_class_adapters import (
    has_semi_russian_or_english_leak,
    ru_prose_ok,
    sanitize_ru_prose,
)
from structure_en_ru_adapt import has_banned_filler
from structure_ru_helpers import cyrillic_count

# Keys: what, why, contains, responsibilities, when, connected, layer (EN)
#       what_ru, why_ru, contains_ru, responsibilities_ru, when_ru, connected_ru, layer_ru (RU)
DOC_PATH_GUIDES: dict[str, dict[str, str]] = {
    "docs/APP_STRUCTURE.md": {
        "what": "Concise map of folders, layers, import rules, and guard commands.",
        "what_ru": "Краткая карта структуры repo — папки, слои, import rules и команды architecture guard.",
        "why": "Quick answer to ‘where does X live?’ without reading the full encyclopedia.",
        "why_ru": "Быстрый ответ «где живёт X» без чтения полной encyclopedia по каждому файлу.",
        "contains": "Tables of `lib/data`, features, scripts; architecture guard entry points.",
        "contains_ru": "Таблицы `lib/data`, features, scripts; команды `architecture_guard.ps1`.",
        "responsibilities": "Canonical structure contract referenced by guard and AI assistants.",
        "responsibilities_ru": "Канонический structure contract для guard и AI — не дублировать ownership в чате.",
        "when": "Finding module ownership; before moving or renaming files.",
        "when_ru": "Ищете ownership модуля; перед переносом файлов или спором «куда положить код».",
        "connected": "`APP_STRUCTURE_DETAILED.md`, `architecture_guard.ps1`.",
        "connected_ru": "`docs/APP_STRUCTURE_DETAILED.md`, `scripts/audit/architecture_guard.ps1`.",
        "layer": "Governing structure doc — Project Knowledge pack.",
        "layer_ru": "Governing structure doc — Project Knowledge pack.",
    },
    "docs/APP_STRUCTURE_DETAILED.md": {
        "what": "Full owner-readable encyclopedia of every tracked folder and file (EN + RU), generated from the repo tree.",
        "what_ru": "Полная owner-readable encyclopedia каждой tracked папки и файла (EN+RU), генерируется из дерева repo.",
        "why": "Source text for the HTML owner map and deep onboarding; complements the concise `APP_STRUCTURE.md`.",
        "why_ru": "Источник для HTML owner map и глубокого onboarding; дополняет краткий `APP_STRUCTURE.md`.",
        "contains": "Per-path EN/RU blocks: what, why, contains, responsibilities, when, delete, connected, layer.",
        "contains_ru": "Блоки EN/RU на каждый путь: что, зачем, содержимое, обязанности, когда открывать, удаление, связи, слой.",
        "responsibilities": "Explain every tracked path in plain language for owner and AI; regenerate after tree changes.",
        "responsibilities_ru": "Объяснить каждый tracked путь plain language для owner и AI; перегенерировать после изменений дерева.",
        "when": "Onboarding, auditing repo necessity, or checking what a path does before editing.",
        "when_ru": "Onboarding, audit «нужен ли файл», проверка роли пути перед правкой.",
        "connected": "`generate_app_structure_detailed.py`, `APP_STRUCTURE.md`, `PROJECT_KNOWLEDGE_PACK.md`.",
        "connected_ru": "`scripts/manual/generate_app_structure_detailed.py`, `docs/APP_STRUCTURE.md`.",
        "layer": "Generated structure encyclopedia — Project Knowledge pack.",
        "layer_ru": "Сгенерированная structure encyclopedia — Project Knowledge pack.",
    },
    "docs/ARCHITECTURE.md": {
        "what": "Iron Laws — optimistic UI, Brain/UI split, PocketBase rules, main-thread and performance kill-switch law.",
        "what_ru": "Iron Laws проекта — optimistic UI, Brain/UI split, PocketBase rules, main-thread law и performance kill switch.",
        "why": "Authoritative technical contract for how the system must behave under load and offline.",
        "why_ru": "Авторитетный технический контракт: как система обязана работать под нагрузкой и офлайн.",
        "contains": "Data flow, offline outboxes, singleton running record, anti-spam polling, performance law.",
        "contains_ru": "Data flow, offline outboxes, singleton record, anti-spam polling, performance kill switch.",
        "responsibilities": "Answer ‘how must the app work?’ before refactors or new Brain/UI patterns.",
        "responsibilities_ru": "Ответ на «как система обязана работать» — до refactor Brain или новых UI паттернов.",
        "when": "Architecture disputes, performance regressions, or optimistic UI violations.",
        "when_ru": "Спор об architecture; регресс performance; нарушение optimistic UI.",
        "connected": "`docs/DATA_MAP.md`, `docs/POCKETBASE_MANIFEST.md`, `docs/UX_CONTRACT.md`.",
        "connected_ru": "`docs/DATA_MAP.md`, `docs/POCKETBASE_MANIFEST.md`, `docs/UX_CONTRACT.md`.",
        "layer": "Governing architecture doc — Project Knowledge pack.",
        "layer_ru": "Governing architecture doc — Project Knowledge pack.",
    },
    "docs/DATA_MAP.md": {
        "what": "Field dictionary for PocketBase — column names, business IDs, relation fields.",
        "what_ru": "Словарь полей PocketBase — имена колонок, business IDs, relation fields.",
        "why": "Brain and UI must POST/PATCH the same field names; prevents invented alternate keys.",
        "why_ru": "Brain и UI должны использовать одни имена полей при POST/PATCH — без выдуманных ключей.",
        "contains": "Tables for records, plans, categories, tags, profiles and relation semantics.",
        "contains_ru": "Таблицы records, plans, categories, tags, profiles и semantics relations.",
        "responsibilities": "Single source of truth for field names aligned with `lib/data/models/`.",
        "responsibilities_ru": "SSOT имён полей — согласован с `lib/data/models/` и PB schema.",
        "when": "Parse errors on PB fields; adding or renaming a schema field.",
        "when_ru": "Ошибка parse поля PB; добавление или переименование поля в schema.",
        "connected": "`docs/POCKETBASE_MANIFEST.md`, `lib/data/models/`.",
        "connected_ru": "`docs/POCKETBASE_MANIFEST.md`, `lib/data/models/`.",
        "layer": "Governing data doc — Project Knowledge pack.",
        "layer_ru": "Governing data doc — Project Knowledge pack.",
    },
    "docs/DEPLOY.md": {
        "what": "Step-by-step deploy — GitHub Pages web app, PocketBase auth admin, Windows installer.",
        "what_ru": "Пошаговый deploy — GitHub Pages, PocketBase auth admin, Windows installer.",
        "why": "Deploy and OAuth break easily without VPS checklist and `update.ps1` order.",
        "why_ru": "Deploy и OAuth легко сломать без VPS checklist и правильного порядка `update.ps1`.",
        "contains": "`update.ps1`, GitHub Pages base href, Windows installer, OAuth admin steps.",
        "contains_ru": "`update.ps1`, GitHub Pages base href, Windows installer, шаги OAuth admin.",
        "responsibilities": "Publish site and configure production auth without guessing server steps.",
        "responsibilities_ru": "Опубликовать сайт и настроить production auth без догадок на сервере.",
        "when": "Site not updating after merge; OAuth broken; building `CounterSetup.exe`.",
        "when_ru": "Сайт не обновился после merge; OAuth broken; сборка `CounterSetup.exe`.",
        "connected": "`.github/workflows/`, `update.ps1`, `installer/windows/`.",
        "connected_ru": "`.github/workflows/`, `update.ps1`, `installer/windows/`.",
        "layer": "Deploy guide — Project Knowledge pack.",
        "layer_ru": "Deploy guide — Project Knowledge pack.",
    },
    "docs/DESIGN_SYSTEM.md": {
        "what": "Design system contract — Figma → Flutter mapping and canonical shared components.",
        "what_ru": "Design system контракт — Figma → Flutter mapping и canonical shared components.",
        "why": "Forbids local copies of buttons/cards in feature screens; V7 migration target.",
        "why_ru": "Запрещает локальные копии кнопок/карточек в feature screens; цель V7 migration.",
        "contains": "Token categories, `AppButton`, `AppIconButton`, forbidden raw Material in features.",
        "contains_ru": "Token categories, `AppButton`, `AppIconButton`, запрет raw Material в features.",
        "responsibilities": "Rules for Component Lab acceptance and production UI migration.",
        "responsibilities_ru": "Правила acceptance в Component Lab и migration production UI.",
        "when": "Migrating UI to canonical widgets; pixel QA against Figma.",
        "when_ru": "Migration UI на canonical widgets; pixel QA против Figma.",
        "connected": "`lib/core/widgets/`, `docs/reports/DESIGN_SYSTEM_INVENTORY.md`, Component Lab.",
        "connected_ru": "`lib/core/widgets/`, `docs/reports/DESIGN_SYSTEM_INVENTORY.md`, Component Lab.",
        "layer": "Governing design doc — Project Knowledge pack.",
        "layer_ru": "Governing design doc — Project Knowledge pack.",
    },
    "docs/POCKETBASE_MANIFEST.md": {
        "what": "Production PocketBase law — base URL, collections, auth, relations, expand paths, hooks, server rules.",
        "what_ru": "Закон production PocketBase — collections, URLs, auth/providers, hooks, ожидания сервера и факты schema/deploy.",
        "why": "Client Brain must not invent URL shapes, relation payloads, or hook behavior.",
        "why_ru": "Brain не должен выдумывать URL shapes, relation payloads или поведение hooks на VPS.",
        "contains": "Collection table, auth id law, API routes, `pb_hooks/` deployment notes, rule intent.",
        "contains_ru": "Таблица collections, auth id law, API routes, deploy `pb_hooks/`, intent API rules.",
        "responsibilities": "Single manifest for how Counter talks to PocketBase in production.",
        "responsibilities_ru": "Единый manifest: как Counter общается с PocketBase в production.",
        "when": "PB 401/403, wrong expand, hook deploy, or schema mismatch with `DATA_MAP.md`.",
        "when_ru": "PB 401/403, неверный expand, deploy hook, расхождение schema с `DATA_MAP.md`.",
        "connected": "`lib/data/pb_config.dart`, `docs/DATA_MAP.md`, `pb_hooks/`.",
        "connected_ru": "`lib/data/pb_config.dart`, `docs/DATA_MAP.md`, `pb_hooks/`.",
        "layer": "Governing PocketBase doc — Project Knowledge pack.",
        "layer_ru": "Governing PocketBase doc — Project Knowledge pack.",
    },
    "docs/PROJECT_KNOWLEDGE_PACK.md": {
        "what": "Upload checklist for Claude Project Knowledge — which 14 docs to attach, which stay repo-only.",
        "what_ru": "Чеклист upload для AI Project Knowledge: какие docs загружать, какие остаются только в repo.",
        "why": "Owner limit (~25 uploads); this file is meta — not architecture law itself.",
        "why_ru": "Лимит upload у owner (~25 файлов); это meta-чеклист, а не architecture law.",
        "contains": "Included pack list, excluded repo-only docs, removed-doc log.",
        "contains_ru": "Список 14 docs для upload, excluded repo-only, log удалённых docs.",
        "responsibilities": "Tell owner/AI what to upload without duplicating governing docs incorrectly.",
        "responsibilities_ru": "Сказать owner/AI что uploadить — без путаницы governing docs и repo-only.",
        "when": "Refreshing Claude Project files or arguing which doc is authoritative.",
        "when_ru": "Обновление Project Knowledge или спор «какой doc канонический».",
        "connected": "The 14 governing docs listed inside; `docs/APP_STRUCTURE.md`.",
        "connected_ru": "14 governing docs внутри файла; `docs/APP_STRUCTURE.md`.",
        "layer": "Meta checklist — repo-only, not uploaded as law.",
        "layer_ru": "Meta-чеклист — repo-only, не architecture law.",
    },
    "docs/ROADMAP.md": {
        "what": "Current work plan — shipped/WIP priorities, V3/V7 focus, paused feature scope, what to do next.",
        "what_ru": "Текущий план работ: shipped/WIP приоритеты, фокус V3/V7, paused feature scope и что делать дальше.",
        "why": "Single canonical plan so AI and owner do not maintain a second roadmap elsewhere.",
        "why_ru": "Единый canonical plan — чтобы AI и owner не вели второй roadmap в других файлах.",
        "contains": "Correctness vs velocity tracks, phase status, O1/V1/F1 shipped notes, active V3/V7 scope.",
        "contains_ru": "Correctness vs velocity tracks, статусы фаз, shipped O1/V1/F1, активный scope V3/V7.",
        "responsibilities": "Prioritize bugs and compounding tidy work before new feature scope.",
        "responsibilities_ru": "Приоритизировать bugs и compounding tidy work перед новым feature scope.",
        "when": "Before planning new feature work or choosing the next session goal.",
        "when_ru": "Перед планированием новой feature work или выбором цели следующей сессии.",
        "connected": "`docs/UX_CONTRACT.md`, `docs/DESIGN_SYSTEM.md`, `docs/ARCHITECTURE.md`.",
        "connected_ru": "`docs/UX_CONTRACT.md`, `docs/DESIGN_SYSTEM.md`, `docs/ARCHITECTURE.md`.",
        "layer": "Governing plan doc — Project Knowledge pack.",
        "layer_ru": "Governing plan doc — Project Knowledge pack.",
    },
    "docs/UX_CONTRACT.md": {
        "what": "Tap-first UX rules — save/loading/offline behavior, optimistic UI, banners, user-visible contracts.",
        "what_ru": "Tap-first UX rules: save/loading/offline, optimistic UI, banners и контракты поведения для пользователя.",
        "why": "Behavioral source beside `ARCHITECTURE.md`; screens must follow before inventing new patterns.",
        "why_ru": "Behavioral source рядом с `ARCHITECTURE.md`; экраны обязаны следовать до новых паттернов.",
        "contains": "100ms feedback, shadow state, debounced errors, empty/loading/offline, sheet close rules.",
        "contains_ru": "100ms feedback, shadow state, debounced errors, empty/loading/offline, правила sheet close.",
        "responsibilities": "Define how taps, saves, and sync banners must feel to the user.",
        "responsibilities_ru": "Как taps, saves и sync banners должны ощущаться пользователю.",
        "when": "Before changing interaction flows, edit sheets, or offline banner behavior.",
        "when_ru": "Перед изменением interaction flows, edit sheets или offline banner.",
        "connected": "`docs/ARCHITECTURE.md`, `lib/app_shell.dart` offline bar, `docs/DESIGN_SYSTEM.md`.",
        "connected_ru": "`docs/ARCHITECTURE.md`, offline bar в `app_shell.dart`, `docs/DESIGN_SYSTEM.md`.",
        "layer": "Governing UX doc — Project Knowledge pack.",
        "layer_ru": "Governing UX doc — Project Knowledge pack.",
    },
    "docs/reports/DESIGN_SYSTEM_INVENTORY.md": {
        "what": "Audit inventory of raw vs canonical UI — what feature screens still use forbidden local widgets.",
        "what_ru": "Audit inventory raw vs canonical UI — какие feature screens ещё используют forbidden local widgets.",
        "why": "V7 migration needs a scoped list before replacing buttons/cards screen by screen.",
        "why_ru": "V7 migration нужен scoped list перед заменой buttons/cards по экранам.",
        "contains": "Classification legend, per-screen raw `FilledButton`/`IconButton` counts, migration status.",
        "contains_ru": "Classification legend, per-screen counts raw buttons, статус migration.",
        "responsibilities": "Track design-system debt; pair with Component Lab acceptance.",
        "responsibilities_ru": "Отслеживать design-system debt; в паре с Component Lab acceptance.",
        "when": "Planning V7 UI migration or verifying a screen is canonical-compliant.",
        "when_ru": "Планирование V7 UI migration или проверка canonical-compliance экрана.",
        "connected": "`docs/DESIGN_SYSTEM.md`, `lib/features/dev/component_lab_view.dart`.",
        "connected_ru": "`docs/DESIGN_SYSTEM.md`, `lib/features/dev/component_lab_view.dart`.",
        "layer": "Repo-only audit report — not Project Knowledge pack.",
        "layer_ru": "Repo-only audit report — не Project Knowledge pack.",
    },
    "docs/reports/FINAL_STRUCTURE_PARITY_AND_DOC_CLEANUP_2026-07-03.md": {
        "what": "Session report — structure parity fixes and APP_STRUCTURE_DETAILED doc cleanup acceptance criteria.",
        "what_ru": "Отчёт сессии — structure parity fixes и критерии приёмки cleanup `APP_STRUCTURE_DETAILED`.",
        "why": "Records what was verified fixed so later sessions do not re-debate the same doc gates.",
        "why_ru": "Фиксирует что уже verified fixed — чтобы следующие сессии не спорили о тех же doc gates.",
        "contains": "Before/after notes, quality gate checklist, paths touched in generator scripts.",
        "contains_ru": "Before/after notes, checklist quality gate, пути в generator scripts.",
        "responsibilities": "Historical evidence for 2026-07-03 structure/doc cleanup arc.",
        "responsibilities_ru": "Историческое evidence для arc structure/doc cleanup 2026-07-03.",
        "when": "Checking why a doc quality rule exists or what ‘accepted’ meant that day.",
        "when_ru": "Проверка почему существует doc quality rule или что значило «accepted» в тот день.",
        "connected": "`docs/APP_STRUCTURE_DETAILED.md`, `generate_app_structure_detailed.py`.",
        "connected_ru": "`docs/APP_STRUCTURE_DETAILED.md`, `generate_app_structure_detailed.py`.",
        "layer": "Repo-only session report.",
        "layer_ru": "Repo-only session report.",
    },
    "docs/reports/FINAL_STRUCTURE_AUDIT_2026-07-06.md": {
        "what": "Final repository structure audit — inventory, boundaries, long-file watchlist, doc parity, Structure Growth Law verdict.",
        "what_ru": "Финальный structure audit repo — inventory, boundaries, long-file watchlist, doc parity, verdict Structure Growth Law.",
        "why": "Records 2026-07-06 acceptance baseline so future work knows what to monitor without re-debating Pass 3–4D.",
        "why_ru": "Фиксирует acceptance baseline 2026-07-06 — что monitor без re-debate Pass 3–4D.",
        "contains": "Commands run, inventory table, architecture guard results, long-file table, duplicate-responsibility watchlist, verdict.",
        "contains_ru": "Commands run, inventory table, architecture guard, long-file table, duplicate watchlist, verdict.",
        "responsibilities": "Authoritative structure health snapshot for owner and AI; repo-only, not Project Knowledge pack.",
        "responsibilities_ru": "Authoritative snapshot здоровья structure для owner и AI; repo-only, не Project Knowledge pack.",
        "when": "Before large refactors, new feature folders, or arguing whether structure is still healthy.",
        "when_ru": "Перед large refactors, new feature folders или спором «structure ещё healthy?».",
        "connected": "`docs/APP_STRUCTURE.md` §7, `docs/ARCHITECTURE.md` §11, `architecture_guard.ps1`.",
        "connected_ru": "`docs/APP_STRUCTURE.md` §7, `docs/ARCHITECTURE.md` §11, `architecture_guard.ps1`.",
        "layer": "Repo-only final audit report.",
        "layer_ru": "Repo-only final audit report.",
    },
    "docs/reports/LARGE_FILE_DECOMPOSITION_PLAN_2026-07-06.md": {
        "what": "Staged decomposition queue for large Dart files — responsibility maps, split targets, risk matrix, execution order.",
        "what_ru": "Поэтапная очередь декомпозиции крупных Dart-файлов — карты ответственности, цели split, матрица рисков, порядок выполнения.",
        "why": "Watchlist files must not keep growing; splits need seams and tests before Brain moves.",
        "why_ru": "Watchlist-файлы не должны расти бесконечно; split требует швов и тестов до Brain moves.",
        "contains": "Top-10 table, per-file maps for plan_service/planning_page/etc., Stage A–E queue, first implementation prompt.",
        "contains_ru": "Таблица top-10, per-file maps, очередь Stage A–E, первый implementation prompt.",
        "responsibilities": "Report-only roadmap — no refactors until an stage prompt is explicitly approved.",
        "responsibilities_ru": "Только отчёт — без рефакторинга до явного одобрения stage prompt.",
        "when": "Before adding features to files over 1000 lines or starting Pass 5 decomposition.",
        "when_ru": "Перед feature work в файлах >1000 строк или стартом Pass 5 decomposition.",
        "connected": "`FINAL_STRUCTURE_AUDIT_2026-07-06.md`, `docs/APP_STRUCTURE.md` §8, §11 ARCHITECTURE.",
        "connected_ru": "`FINAL_STRUCTURE_AUDIT_2026-07-06.md`, `docs/APP_STRUCTURE.md` §8.",
        "layer": "Repo-only decomposition plan.",
        "layer_ru": "Repo-only decomposition plan.",
    },
    "docs/reports/FULL_REPO_NECESSITY_CLEANUP_2026-07-03.md": {
        "what": "Full-repo necessity audit — which tracked paths are required vs optional hygiene.",
        "what_ru": "Full-repo necessity audit — какие tracked paths обязательны vs optional hygiene.",
        "why": "Supports deleting or ignoring dead files without breaking build, deploy, or governing docs.",
        "why_ru": "Помогает удалять dead files без поломки build, deploy или governing docs.",
        "contains": "Tier labels, platform vs app vs docs classification, cleanup recommendations.",
        "contains_ru": "Tier labels, классификация platform vs app vs docs, рекомендации cleanup.",
        "responsibilities": "Answer ‘can we delete this folder?’ with evidence, not guesswork.",
        "responsibilities_ru": "Ответ «можно ли удалить эту папку?» с evidence, не guesswork.",
        "when": "Repo bloat debate, pre-commit cleanup, or onboarding ‘what is safe to ignore’.",
        "when_ru": "Спор о repo bloat, pre-commit cleanup, onboarding «что safe ignore».",
        "connected": "`docs/APP_STRUCTURE_DETAILED.md`, `docs/APP_STRUCTURE.md`.",
        "connected_ru": "`docs/APP_STRUCTURE_DETAILED.md`, `docs/APP_STRUCTURE.md`.",
        "layer": "Repo-only audit report.",
        "layer_ru": "Repo-only audit report.",
    },
    "docs/website/CONTENT_LIBRARY.md": {
        "what": "Website content library — reusable EN/RU blocks for CMS, designers, and copywriters.",
        "what_ru": "Content library сайта — переиспользуемые EN/RU блоки для CMS, designers и copywriters.",
        "why": "Ensures product names, positioning, and feature blurbs stay consistent across pages.",
        "why_ru": "Держит product names, positioning и feature blurbs согласованными между страницами.",
        "contains": "Product names table, positioning statements, feature one-liners, FAQ snippets.",
        "contains_ru": "Таблица product names, positioning statements, feature one-liners, FAQ snippets.",
        "responsibilities": "Source blocks for `PUBLIC_COPY_DRAFTS.md` and future static site pages.",
        "responsibilities_ru": "Source blocks для `PUBLIC_COPY_DRAFTS.md` и будущих static pages.",
        "when": "Writing or translating marketing copy; avoiding duplicate phrasing across pages.",
        "when_ru": "Написание/перевод marketing copy; избежание duplicate phrasing между страницами.",
        "connected": "`docs/website/PUBLIC_COPY_DRAFTS.md`, `docs/website/FEATURE_MATRIX.md`.",
        "connected_ru": "`docs/website/PUBLIC_COPY_DRAFTS.md`, `docs/website/FEATURE_MATRIX.md`.",
        "layer": "Repo-only marketing content — not Project Knowledge pack.",
        "layer_ru": "Repo-only marketing content — не Project Knowledge pack.",
    },
    "docs/website/FEATURE_MATRIX.md": {
        "what": "Website feature matrix — which product capabilities appear on v1 site vs deferred.",
        "what_ru": "Feature matrix сайта — какие capabilities продукта на v1 site vs deferred.",
        "why": "Prevents over-promising on landing pages; aligns with `WEBSITE_V1_SCOPE.md`.",
        "why_ru": "Не over-promise на landing; согласован с `WEBSITE_V1_SCOPE.md`.",
        "contains": "Tier tables (hero / soft / excluded), platform and honesty flags per feature.",
        "contains_ru": "Tier tables (hero / soft / excluded), platform и honesty flags по feature.",
        "responsibilities": "Gate marketing claims against real shipped app behavior.",
        "responsibilities_ru": "Gate marketing claims против реального shipped behavior приложения.",
        "when": "Choosing hero screenshots or writing Features page bullets.",
        "when_ru": "Выбор hero screenshots или bullets для Features page.",
        "connected": "`docs/website/WEBSITE_V1_SCOPE.md`, `docs/website/WEBSITE_CLAIMS_REVIEW.md`.",
        "connected_ru": "`docs/website/WEBSITE_V1_SCOPE.md`, `docs/website/WEBSITE_CLAIMS_REVIEW.md`.",
        "layer": "Repo-only marketing planning.",
        "layer_ru": "Repo-only marketing planning.",
    },
    "docs/website/HOMEPAGE_WIREFRAME_V1.md": {
        "what": "Homepage wireframe v1 — section order, hero, feature strips, FAQ teaser, primary CTA.",
        "what_ru": "Homepage wireframe v1 — порядок секций, hero, feature strips, FAQ teaser, primary CTA.",
        "why": "Static v1 landing must fit one scroll story before pixel implementation.",
        "why_ru": "Static v1 landing должен уложиться в one scroll story до pixel implementation.",
        "contains": "ASCII/block layout notes, CTA placement, screenshot slots.",
        "contains_ru": "ASCII/block layout notes, placement CTA, слоты screenshots.",
        "responsibilities": "Blueprint for `/` or `/index.html` marketing shell beside Flutter web app.",
        "responsibilities_ru": "Blueprint для marketing shell `/` рядом с Flutter web app.",
        "when": "Designing or implementing the public homepage layout.",
        "when_ru": "Design или implementation layout public homepage.",
        "connected": "`docs/website/WEBSITE_PAGE_STRUCTURE.md`, `docs/website/SCREENSHOT_SHOTLIST.md`.",
        "connected_ru": "`docs/website/WEBSITE_PAGE_STRUCTURE.md`, `docs/website/SCREENSHOT_SHOTLIST.md`.",
        "layer": "Repo-only marketing wireframe.",
        "layer_ru": "Repo-only marketing wireframe.",
    },
    "docs/website/INTERNAL_NOTES_NOT_FOR_SITE.md": {
        "what": "Internal website notes — strategy and risks not for public copy.",
        "what_ru": "Internal notes по сайту — strategy и risks не для public copy.",
        "why": "Separates honest internal debate from visitor-facing drafts.",
        "why_ru": "Отделяет honest internal debate от visitor-facing drafts.",
        "contains": "Open questions, competitor notes, defer lists, tone guardrails.",
        "contains_ru": "Открытые вопросы, заметки о конкурентах, defer lists, tone guardrails.",
        "responsibilities": "Owner-only context; must not be pasted into live site verbatim.",
        "responsibilities_ru": "Owner-only context; нельзя paste verbatim на live site.",
        "when": "Deciding positioning trade-offs without polluting public drafts.",
        "when_ru": "Trade-offs positioning без загрязнения public drafts.",
        "connected": "`docs/website/POSITIONING_V1.md`, `exports/` if present.",
        "connected_ru": "`docs/website/POSITIONING_V1.md`, `exports/` если есть.",
        "layer": "Repo-only internal notes.",
        "layer_ru": "Repo-only internal notes.",
    },
    "docs/website/POSITIONING_V1.md": {
        "what": "Website positioning v1 — promise, audience, differentiation vs generic time trackers.",
        "what_ru": "Positioning v1 сайта — promise, audience, отличие от обычных time trackers.",
        "why": "Hero and meta description must say one clear sentence, not feature soup.",
        "why_ru": "Hero и meta description должны давать one clear sentence, не feature soup.",
        "contains": "Headline options, anti-patterns, traveler/offline angles.",
        "contains_ru": "Варианты headline, anti-patterns, traveler/offline angles.",
        "responsibilities": "Anchor all v1 public copy to the same product promise.",
        "responsibilities_ru": "Якорь всего v1 public copy на одном product promise.",
        "when": "Rewriting hero, tagline, or social preview text.",
        "when_ru": "Rewrite hero, tagline или social preview text.",
        "connected": "`docs/website/CONTENT_LIBRARY.md`, `docs/website/PUBLIC_COPY_DRAFTS.md`.",
        "connected_ru": "`docs/website/CONTENT_LIBRARY.md`, `docs/website/PUBLIC_COPY_DRAFTS.md`.",
        "layer": "Repo-only marketing positioning.",
        "layer_ru": "Repo-only marketing positioning.",
    },
    "docs/website/PRODUCT_INVENTORY.md": {
        "what": "Product inventory for website — shipped surfaces mapped to marketing names.",
        "what_ru": "Product inventory для сайта — shipped surfaces с marketing names.",
        "why": "Copywriters need accurate feature names tied to real tabs and flows.",
        "why_ru": "Copywriters нужны accurate feature names, привязанные к real tabs и flows.",
        "contains": "Tab index map, feature aliases, screenshot-friendly labels.",
        "contains_ru": "Tab index map, feature aliases, подписи для screenshots.",
        "responsibilities": "Prevent website from inventing features the app does not ship.",
        "responsibilities_ru": "Не дать сайту invent features, которых нет в shipped app.",
        "when": "Naming Features page sections or tour captions.",
        "when_ru": "Naming секций Features page или tour captions.",
        "connected": "`docs/APP_STRUCTURE.md`, `docs/website/FEATURE_MATRIX.md`.",
        "connected_ru": "`docs/APP_STRUCTURE.md`, `docs/website/FEATURE_MATRIX.md`.",
        "layer": "Repo-only product/marketing bridge.",
        "layer_ru": "Repo-only product/marketing bridge.",
    },
    "docs/website/PUBLIC_COPY_DRAFTS.md": {
        "what": "Public copy drafts — polished EN/RU visitor text ready for static pages.",
        "what_ru": "Черновики public copy — polished EN/RU visitor text для static pages.",
        "why": "Separates draft polish from internal notes and content library atoms.",
        "why_ru": "Отделяет draft polish от internal notes и atoms content library.",
        "contains": "Page-ready paragraphs, FAQ answers, CTA strings.",
        "contains_ru": "Готовые абзацы страниц, FAQ answers, CTA strings.",
        "responsibilities": "Candidate text for GitHub Pages marketing shell — review before publish.",
        "responsibilities_ru": "Candidate text для marketing shell GitHub Pages — review перед publish.",
        "when": "Implementing HTML pages or reviewing tone before deploy.",
        "when_ru": "Implementation HTML pages или review tone перед deploy.",
        "connected": "`docs/website/CONTENT_LIBRARY.md`, `docs/website/WEBSITE_CLAIMS_REVIEW.md`.",
        "connected_ru": "`docs/website/CONTENT_LIBRARY.md`, `docs/website/WEBSITE_CLAIMS_REVIEW.md`.",
        "layer": "Repo-only public copy drafts.",
        "layer_ru": "Repo-only public copy drafts.",
    },
    "docs/website/SCREENSHOT_SHOTLIST.md": {
        "what": "Screenshot shotlist — six curated captures, captions, and honesty notes for v1 tour.",
        "what_ru": "Screenshot shotlist — шесть curated captures, captions и honesty notes для v1 tour.",
        "why": "Tour page quality depends on planned shots, not random emulator grabs.",
        "why_ru": "Tour page quality зависит от planned shots, не random emulator grabs.",
        "contains": "Per-shot route, device density, caption EN/RU, soft-claim warnings.",
        "contains_ru": "Per-shot route, device density, caption EN/RU, предупреждения soft-claim.",
        "responsibilities": "Define which UI states must be captured before website launch.",
        "responsibilities_ru": "Какие UI states capture перед website launch.",
        "when": "Preparing `/tour` gallery or marketing assets export.",
        "when_ru": "Подготовка gallery `/tour` или export marketing assets.",
        "connected": "`docs/website/HOMEPAGE_WIREFRAME_V1.md`, `docs/website/WEBSITE_V1_SCOPE.md`.",
        "connected_ru": "`docs/website/HOMEPAGE_WIREFRAME_V1.md`, `docs/website/WEBSITE_V1_SCOPE.md`.",
        "layer": "Repo-only marketing asset plan.",
        "layer_ru": "Repo-only marketing asset plan.",
    },
    "docs/website/WEBSITE_CLAIMS_REVIEW.md": {
        "what": "Website claims review — fact-check marketing statements against shipped app behavior.",
        "what_ru": "Claims review сайта — fact-check marketing statements против shipped app behavior.",
        "why": "Prevents false promises (auto-save, drag Time View, store badges) on public pages.",
        "why_ru": "Предотвращает false promises (auto-save, drag Time View, store badges) на public pages.",
        "contains": "Claim / evidence / verdict table, red-line exclusions for v1.",
        "contains_ru": "Таблица claim / evidence / verdict, red-line exclusions для v1.",
        "responsibilities": "Legal-honest gate before any copy goes live.",
        "responsibilities_ru": "Legal-honest gate перед publish любого copy.",
        "when": "Editing hero, FAQ, or Features page; before approving deploy.",
        "when_ru": "Правка hero, FAQ или Features page; перед approve deploy.",
        "connected": "`docs/website/FEATURE_MATRIX.md`, `docs/UX_CONTRACT.md`.",
        "connected_ru": "`docs/website/FEATURE_MATRIX.md`, `docs/UX_CONTRACT.md`.",
        "layer": "Repo-only claims audit.",
        "layer_ru": "Repo-only claims audit.",
    },
    "docs/website/WEBSITE_IMPLEMENTATION_OPTIONS.md": {
        "what": "Website implementation options — static HTML vs generator vs Flutter-adjacent trade-offs.",
        "what_ru": "Варианты реализации сайта — static HTML, generator или Flutter-adjacent подходы.",
        "why": "Marketing site must not break `/Counter/` Flutter web deploy path.",
        "why_ru": "Marketing site не должен ломать deploy path Flutter web `/Counter/`.",
        "contains": "Pros/cons tables, GitHub Pages constraints, base href notes.",
        "contains_ru": "Pros/cons tables, ограничения GitHub Pages, notes base href.",
        "responsibilities": "Choose build approach for v1 without forking app release pipeline.",
        "responsibilities_ru": "Выбор build approach для v1 без fork app release pipeline.",
        "when": "Starting website code or arguing static vs integrated hosting.",
        "when_ru": "Старт website code или спор static vs integrated hosting.",
        "connected": "`docs/DEPLOY.md`, `docs/website/WEBSITE_V1_SCOPE.md`.",
        "connected_ru": "`docs/DEPLOY.md`, `docs/website/WEBSITE_V1_SCOPE.md`.",
        "layer": "Repo-only implementation planning.",
        "layer_ru": "Repo-only implementation planning.",
    },
    "docs/website/WEBSITE_PAGE_STRUCTURE.md": {
        "what": "Website page structure — v2+ full sitemap reference (routes, nav, page purposes).",
        "what_ru": "Page structure сайта — v2+ full sitemap reference (routes, nav, purposes страниц).",
        "why": "v1 uses fewer pages; this doc holds the longer information architecture target.",
        "why_ru": "v1 использует меньше pages; здесь longer information architecture target.",
        "contains": "Route list, nav hierarchy, deferred pages beyond v1 scope.",
        "contains_ru": "Список routes, nav hierarchy, отложенные pages beyond v1 scope.",
        "responsibilities": "Future expansion map — do not treat every route as v1 commitment.",
        "responsibilities_ru": "Future expansion map — не каждый route = v1 commitment.",
        "when": "Planning v2 SEO split or additional marketing routes.",
        "when_ru": "Планирование v2 SEO split или дополнительных marketing routes.",
        "connected": "`docs/website/WEBSITE_V1_SCOPE.md`, `docs/website/HOMEPAGE_WIREFRAME_V1.md`.",
        "connected_ru": "`docs/website/WEBSITE_V1_SCOPE.md`, `docs/website/HOMEPAGE_WIREFRAME_V1.md`.",
        "layer": "Repo-only IA reference.",
        "layer_ru": "Repo-only IA reference.",
    },
    "docs/website/WEBSITE_TZ.md": {
        "what": "Website TZ (technical brief) — timezone and legal copy requirements for public pages.",
        "what_ru": "TZ сайта (technical brief) — timezone и legal copy requirements для public pages.",
        "why": "FAQ must honestly explain profile timezone vs device time without legal overreach.",
        "why_ru": "FAQ должен honestly explain profile timezone vs device time без legal overreach.",
        "contains": "Timezone FAQ bullets, privacy tone, RU summary section rules for v1.",
        "contains_ru": "Timezone FAQ bullets, privacy tone, правила RU summary section для v1.",
        "responsibilities": "Keep legal/timezone messaging aligned with real app settings UX.",
        "responsibilities_ru": "Legal/timezone messaging согласован с real app settings UX.",
        "when": "Writing FAQ, privacy footer, or RU summary blocks on Home.",
        "when_ru": "FAQ, privacy footer или RU summary blocks на Home.",
        "connected": "`docs/website/PUBLIC_COPY_DRAFTS.md`, profile timezone in app.",
        "connected_ru": "`docs/website/PUBLIC_COPY_DRAFTS.md`, profile timezone в app.",
        "layer": "Repo-only legal/timezone copy brief.",
        "layer_ru": "Repo-only legal/timezone copy brief.",
    },
    "docs/website/WEBSITE_V1_SCOPE.md": {
        "what": "Website v1 scope — max five static pages, hero features, excluded roadmap/store claims.",
        "what_ru": "Website v1 scope — максимум пять static pages, hero features, excluded roadmap/store claims.",
        "why": "Ship one convincing landing before building a product encyclopedia site.",
        "why_ru": "Сначала один убедительный landing, потом encyclopedia site о продукте.",
        "contains": "Included/deferred page tables, messaging tiers, CTA to live web app.",
        "contains_ru": "Included/deferred page tables, messaging tiers, CTA к live web app.",
        "responsibilities": "Cap v1 work; supersedes page list only for implementation, not IA ideas.",
        "responsibilities_ru": "Cap v1 work; supersedes page list только для implementation.",
        "when": "Cutting scope, choosing hero features, or rejecting new page requests.",
        "when_ru": "Cutting scope, выбор hero features или reject new page requests.",
        "connected": "`docs/website/WEBSITE_PAGE_STRUCTURE.md`, `docs/website/FEATURE_MATRIX.md`.",
        "connected_ru": "`docs/website/WEBSITE_PAGE_STRUCTURE.md`, `docs/website/FEATURE_MATRIX.md`.",
        "layer": "Repo-only v1 scope contract.",
        "layer_ru": "Repo-only v1 scope contract.",
    },
}


def doc_path_guide(path: str) -> dict[str, str] | None:
    """Return merged EN+RU guide dict for a docs path, or None."""
    p = path.replace("\\", "/")
    if not p.startswith("docs/") or not p.endswith(".md"):
        return None
    return DOC_PATH_GUIDES.get(p)


def doc_file_ru_field(
    path: str, name: str, field: str, en_val: str, en: dict[str, str]
) -> str | None:
    guide = doc_path_guide(path)
    if not guide:
        return None
    ru_key = f"{field}_ru"
    v = guide.get(ru_key)
    if not v:
        return None
    v = sanitize_ru_prose(v)
    if has_banned_filler(v) or has_semi_russian_or_english_leak(v):
        return None
    if ru_prose_ok(v, min_cyrillic=6):
        return v
    if cyrillic_count(v) >= 4 and "`" in v:
        return v
    return None
