"""Curated meaningful RU for key files — merged in finalize_file_guide."""

from __future__ import annotations

FILE_RU_CURATED: dict[str, dict[str, str]] = {
    ".github/workflows/deploy.yml": {
        "what_ru": "Workflow GitHub Actions для публикации web-версии. После push собирает Flutter web с base href `/Counter/` и выкладывает на GitHub Pages.",
        "why_ru": "Автоматизирует deploy сайта без ручного `update.ps1` на CI runner.",
        "contains_ru": "Шаги checkout, `flutter build web`, deploy в `gh-pages` branch.",
        "responsibilities_ru": "Собрать и опубликовать web build при push в main.",
        "when_ru": "Сайт не обновился после merge; проверка CI deploy log.",
        "connected_ru": "`docs/DEPLOY.md`, `update.ps1`, `web/index.html`.",
        "layer_ru": "CI deploy — не runtime приложения.",
    },
    ".github/workflows/windows-desktop-build.yml": {
        "what_ru": "Workflow GitHub Actions для сборки Windows installer `CounterSetup.exe`.",
        "why_ru": "Автоматизирует release Windows desktop build и упаковку installer artifact.",
        "contains_ru": "Шаги `flutter build windows`, подготовка STT payload, Inno Setup.",
        "responsibilities_ru": "Собрать `.exe` installer и загрузить artifact в Actions.",
        "when_ru": "Нет `CounterSetup.exe` в Actions artifacts после push.",
        "connected_ru": "`installer/windows/`, `docs/DEPLOY.md`.",
        "layer_ru": "CI Windows installer — не runtime приложения.",
    },
    ".github/copilot-instructions.md": {
        "what_ru": "Краткие правила для GitHub Copilot внутри repo — главные ограничения проекта.",
        "why_ru": "Copilot видит architecture laws и не предлагает запрещённые PocketBase/Brain паттерны.",
        "contains_ru": "Markdown с iron rules, ссылками на governing docs.",
        "responsibilities_ru": "Сжатый контекст для Copilot в GitHub UI.",
        "when_ru": "Copilot предлагает refactor, ломающий Brain/UI или optimistic UI.",
        "connected_ru": "`.github/`, `docs/ARCHITECTURE.md`.",
        "layer_ru": "AI instructions — не runtime.",
    },
    "android/app/build.gradle.kts": {
        "what_ru": "Gradle-скрипт модуля `android/app` — SDK, plugins, signing, зависимости APK.",
        "why_ru": "Именно этот module Gradle превращает Flutter Android build в APK/AAB Counter.",
        "contains_ru": "compileSdk, minSdk, Flutter Gradle plugin hook, dependencies.",
        "responsibilities_ru": "Настроить compile/target SDK, plugins Flutter, hooks подписи release.",
        "when_ru": "Ошибка сборки app module, SDK version, signing config.",
        "connected_ru": "`android/settings.gradle.kts`, `AndroidManifest.xml`.",
        "layer_ru": "Android app module build — не Dart UI.",
    },
    "android/build.gradle.kts": {
        "what_ru": "Корневой Gradle-скрипт проекта `android/` — общие версии и classpath плагинов.",
        "why_ru": "Связывает wrapper, AGP и Flutter Gradle plugin для всего Android tree.",
        "contains_ru": "buildscript classpath, allprojects repos, clean task.",
        "responsibilities_ru": "Общие настройки Gradle для root Android project.",
        "when_ru": "Root Gradle sync fail, classpath/plugin version errors.",
        "connected_ru": "`android/settings.gradle.kts`, `android/app/`.",
        "layer_ru": "Android root Gradle — не Dart.",
    },
    "android/settings.gradle.kts": {
        "what_ru": "Gradle settings — подключает модули Android-проекта и версии плагинов.",
        "why_ru": "Gradle читает этот файл первым, чтобы знать какие модули собирать.",
        "contains_ru": "Список include modules, pluginManagement, версии AGP.",
        "responsibilities_ru": "Задать структуру multi-module Gradle проекта Counter.",
        "when_ru": "Gradle sync падает на settings или не видит `:app` module.",
        "connected_ru": "`android/build.gradle.kts`, `android/app/build.gradle.kts`.",
        "layer_ru": "Android Gradle config — не Dart.",
    },
    "android/app/src/main/AndroidManifest.xml": {
        "what_ru": "Android manifest (release/main) — permissions, label приложения и Flutter activity.",
        "why_ru": "Android читает XML при установке: mic, notifications, запуск Counter.",
        "contains_ru": "Теги `<uses-permission>`, application label, intent filters.",
        "responsibilities_ru": "Задать permissions ОС и deep links для release build.",
        "when_ru": "Permission denied на устройстве, неверное имя app, intent filters.",
        "connected_ru": "`android/app/build.gradle.kts`, Kotlin MainActivity.",
        "layer_ru": "Android manifest — не Dart business logic.",
    },
    "android/app/src/debug/AndroidManifest.xml": {
        "what_ru": "Android manifest (debug) — permissions и overrides для debug-сборки.",
        "why_ru": "Debug variant может добавлять или ослаблять permissions для разработки.",
        "contains_ru": "Debug-only manifest merge поверх main manifest.",
        "responsibilities_ru": "Отличия debug build от release на уровне manifest.",
        "when_ru": "Debug APK ведёт себя иначе по permissions чем release.",
        "connected_ru": "`android/app/src/main/AndroidManifest.xml`.",
        "layer_ru": "Android manifest debug — не Dart.",
    },
    "android/app/src/main/kotlin/com/example/counter/MainActivity.kt": {
        "what_ru": "Минимальная Android Activity — поднимает Flutter engine и показывает Dart UI.",
        "why_ru": "Без этой Activity APK не может открыть Flutter интерфейс после tap по иконке.",
        "contains_ru": "Subclass `FlutterActivity` — несколько строк Kotlin.",
        "responsibilities_ru": "Запуск Flutter engine при старте Counter на Android.",
        "when_ru": "Crash при launch Android или native deep link handling.",
        "connected_ru": "`AndroidManifest.xml`, Flutter Android embedding.",
        "layer_ru": "Android entry point — не Dart business logic.",
    },
    "android/app/src/main/res/drawable/launch_background.xml": {
        "what_ru": "XML-фон splash Android — показывается до первого кадра Flutter.",
        "why_ru": "Убирает белую вспышку при cold start, пока engine грузит UI.",
        "contains_ru": "Layer-list drawable с цветом или картинкой фона.",
        "responsibilities_ru": "Native splash до появления Flutter content.",
        "when_ru": "Белая вспышка при launch или неверный цвет splash.",
        "connected_ru": "`styles.xml`, theme в `AndroidManifest.xml`.",
        "layer_ru": "Android drawable resource.",
    },
    "android/app/src/main/res/drawable-v21/launch_background.xml": {
        "what_ru": "XML-фон splash Android (API 21+) — тот же splash для новых версий ОС.",
        "why_ru": "На API 21+ drawable может отличаться от legacy `drawable/` варианта.",
        "contains_ru": "Layer-list drawable для splash на API 21+.",
        "responsibilities_ru": "Native splash на Android 5.0+ до первого Flutter frame.",
        "when_ru": "Splash на новых Android отличается от старых или неверный цвет.",
        "connected_ru": "`drawable/launch_background.xml`, `styles.xml`.",
        "layer_ru": "Android drawable resource.",
    },
    "android/app/src/main/res/values/styles.xml": {
        "what_ru": "XML-стили Android — theme launch и окна приложения.",
        "why_ru": "Задаёт цвета/status bar/splash theme до и после старта Flutter.",
        "contains_ru": "Theme `LaunchTheme`, `NormalTheme`, ссылки на `@drawable/launch_background`.",
        "responsibilities_ru": "Внешний вид native chrome при launch Android.",
        "when_ru": "Неверные цвета splash/status bar на Android.",
        "connected_ru": "`launch_background.xml`, `AndroidManifest.xml`.",
        "layer_ru": "Android styles resource.",
    },
    "android/app/src/main/res/values-night/styles.xml": {
        "what_ru": "XML-стили Android (night) — theme launch и окна в тёмном режиме ОС.",
        "why_ru": "Night resources подхватываются когда система в dark mode.",
        "contains_ru": "Night variants `LaunchTheme` и `NormalTheme`.",
        "responsibilities_ru": "Splash/status bar в dark mode Android.",
        "when_ru": "Splash/status bar неверны только в тёмной теме ОС.",
        "connected_ru": "`values/styles.xml`, `launch_background.xml`.",
        "layer_ru": "Android styles resource (night).",
    },
    "android/app/src/main/res/mipmap-hdpi/ic_launcher.png": {
        "what_ru": "PNG иконка launcher Android (mipmap-hdpi) — иконка Counter на home screen.",
        "why_ru": "Для hdpi нужен отдельный размер PNG, иначе icon blur на экране.",
        "contains_ru": "Растровый PNG `ic_launcher.png` для hdpi.",
        "responsibilities_ru": "Чёткая иконка Counter на устройствах hdpi.",
        "when_ru": "Размытая или неверная иконка на home screen Android.",
        "connected_ru": "`AndroidManifest.xml` application icon.",
        "layer_ru": "Android mipmap asset.",
    },
    "docs/APP_STRUCTURE.md": {
        "what_ru": "Краткая карта структуры repo — папки, слои, import rules, команды guard.",
        "why_ru": "Быстрый ответ «где живёт X» без чтения всей encyclopedia.",
        "contains_ru": "Таблицы `lib/data`, features, scripts; команды architecture guard.",
        "responsibilities_ru": "Канонический structure contract для guard и AI.",
        "when_ru": "Ищете ownership модуля; перед переносом файлов.",
        "connected_ru": "`APP_STRUCTURE_DETAILED.md`, `architecture_guard.ps1`.",
        "layer_ru": "Governing structure doc — Project Knowledge pack.",
    },
    "docs/ARCHITECTURE.md": {
        "what_ru": "Железные законы проекта — optimistic UI, Brain/UI split, PocketBase, main-thread law.",
        "why_ru": "Авторитетный технический контракт для owner и AI.",
        "contains_ru": "Правила data flow, offline, singleton record, performance.",
        "responsibilities_ru": "Ответ на «как система обязана работать».",
        "when_ru": "Спор об architecture; перед refactor Brain или UI.",
        "connected_ru": "`docs/DATA_MAP.md`, `docs/POCKETBASE_MANIFEST.md`.",
        "layer_ru": "Governing architecture doc — Project Knowledge pack.",
    },
    "docs/DATA_MAP.md": {
        "what_ru": "Словарь полей PocketBase — имена колонок, business IDs, relation fields.",
        "why_ru": "Brain и UI должны использовать одни имена полей при POST/PATCH.",
        "contains_ru": "Таблицы records, plans, categories, tags, profiles.",
        "responsibilities_ru": "SSOT имён полей — не выдумывать alternate names.",
        "when_ru": "Ошибка parse поля PB; добавление нового поля в schema.",
        "connected_ru": "`docs/POCKETBASE_MANIFEST.md`, `lib/data/models/`.",
        "layer_ru": "Governing data doc — Project Knowledge pack.",
    },
    "docs/DESIGN_SYSTEM.md": {
        "what_ru": "Design system контракт — Figma → Flutter mapping, canonical components.",
        "why_ru": "Запрещает локальные копии кнопок/карточек в feature screens.",
        "contains_ru": "Token categories, `AppButton`, `AppIconButton`, forbidden local UI.",
        "responsibilities_ru": "Правила V7 component migration и Component Lab acceptance.",
        "when_ru": "Миграция UI на canonical widgets; pixel QA.",
        "connected_ru": "`lib/core/widgets/`, Component Lab.",
        "layer_ru": "Governing design doc — Project Knowledge pack.",
    },
    "docs/DEPLOY.md": {
        "what_ru": "Пошаговый deploy — GitHub Pages, PocketBase auth admin, Windows installer.",
        "why_ru": "Deploy и OAuth легко сломать без VPS checklist.",
        "contains_ru": "`update.ps1`, GitHub Pages flow, Windows installer, OAuth admin steps.",
        "responsibilities_ru": "Инструкция публикации сайта и production auth.",
        "when_ru": "Сайт не обновился; OAuth broken; сборка installer.",
        "connected_ru": "`.github/workflows/`, `update.ps1`, `installer/`.",
        "layer_ru": "Deploy guide — Project Knowledge pack.",
    },
    "android.ps1": {
        "what_ru": "Локальная сборка Android release APK — split per ABI со штампом git commit в About.",
        "why_ru": "Короче ручного `flutter build apk`; подставляет `GIT_COMMIT` и `BUILD_TIME`.",
        "contains_ru": "`flutter pub get` → `flutter build apk --release --split-per-abi`; retry `--no-tree-shake-icons`.",
        "responsibilities_ru": "APK в `build/app/outputs/flutter-apk/` (`app-arm64-v8a-release.apk` для телефонов).",
        "when_ru": "Тест release APK на физическом Android.",
        "connected_ru": "`android/` Gradle, `lib/core/app_build_info.dart`.",
        "layer_ru": "Сборка Android — не runtime логика.",
    },
    "windows/runner/main.cpp": {
        "what_ru": "Точка входа native C++ Windows-приложения. Создаёт Win32 window, инициализирует Flutter engine и запускает Dart UI.",
        "why_ru": "Windows `.exe` стартует отсюда: без `main()` Flutter desktop не поднимет окно Counter.",
        "contains_ru": "`wWinMain`/`main`, вызовы создания окна и `flutter::FlutterViewController`.",
        "responsibilities_ru": "Старт Windows runner: Win32 host и bootstrap Flutter engine.",
        "when_ru": "Windows `.exe` не стартует, crash до первого кадра Flutter.",
        "delete_ru": "Нет — без него Windows `.exe` не запустится.",
    },
    "windows/CMakeLists.txt": {
        "what_ru": "Главный CMake-файл Windows desktop runner. Описывает native targets, source files и link rules, через которые Flutter engine собирается в Windows `.exe`.",
        "why_ru": "CMake configure/link связывает `runner/`, `flutter/` glue и plugin registrant в один desktop binary.",
        "responsibilities_ru": "Собрать Counter Windows `.exe` из native runner + Flutter AOT.",
        "delete_ru": "Нет — без него `flutter build windows` не соберёт `.exe`.",
    },
    "installer/windows/prepare_stt_payload.ps1": {
        "what_ru": "PowerShell-скрипт подготовки STT payload для Windows installer. Копирует/проверяет helper exe, model files и runtime payload перед сборкой Inno Setup.",
        "why_ru": "Inno Setup script ожидает готовый STT bundle — иначе installed app не найдёт speech helper.",
        "responsibilities_ru": "Подготовить STT файлы для `counter.iss` перед сборкой setup.",
        "when_ru": "Installed app не видит speech helper; перед локальной сборкой `CounterSetup.exe`.",
        "delete_ru": "Нет — без него installer STT bundle неполный.",
    },
    "installer/windows/build_stt_helper_en.ps1": {
        "what_ru": "PowerShell-сборка English STT helper для installer. Нужна, чтобы `counter_stt_helper.exe` попал в setup package, а desktop voice работал после установки.",
        "why_ru": "Desktop voice на Windows вызывает GOLOS STT subprocess — exe должен быть собран до Inno Setup.",
        "responsibilities_ru": "Собрать или обновить STT helper binary для installer payload.",
        "delete_ru": "Нет — без него installer не получит свежий STT helper.",
    },
    "installer/windows/stt_helper_build/counter_stt_helper.exe": {
        "what_ru": "Собранный STT helper binary, который installer кладёт рядом с Windows-приложением. Desktop voice вызывает его как subprocess для transcription.",
        "why_ru": "Installed Counter на Windows не использует mobile STT API — нужен отдельный native helper exe.",
        "responsibilities_ru": "Transcription subprocess для desktop voice после установки через setup.",
        "delete_ru": "Нет — удаление ломает voice в installed app.",
    },
    "android/gradle/wrapper/gradle-wrapper.properties": {
        "what_ru": "Gradle Wrapper properties для Android build. Фиксирует Gradle distribution URL/version, чтобы CI и локальная машина запускали одну и ту же Gradle-версию.",
        "why_ru": "Без pinned Gradle version Android sync на CI и у разработчика расходятся.",
        "responsibilities_ru": "Pin Gradle distribution для всего `android/` tree.",
        "delete_ru": "Нет — без него `./gradlew` не скачает нужную Gradle.",
    },
    "ios/Flutter/Debug.xcconfig": {
        "what_ru": "Xcode build configuration для Flutter iOS target (Debug). Передаёт Flutter/CocoaPods settings в Debug сборку.",
        "why_ru": "Xcode читает xcconfig при сборке Runner Debug — без него Flutter flags не попадут в compile.",
        "responsibilities_ru": "Debug compile flags и пути Flutter engine для iOS.",
        "delete_ru": "Нет — без него Debug iOS build или pod integration падает.",
    },
    "ios/Flutter/Release.xcconfig": {
        "what_ru": "Xcode build configuration для Flutter iOS target (Release). Передаёт Flutter/CocoaPods settings в Release/IPA сборку.",
        "why_ru": "Release archive/TestFlight использует эти flags для AOT и stripped build.",
        "responsibilities_ru": "Release compile flags и пути Flutter engine для iOS IPA.",
        "delete_ru": "Нет — без него Release iOS build или pod integration падает.",
    },
    "ios/Runner.xcodeproj/project.pbxproj": {
        "what_ru": "Главная project database Xcode для iOS Runner. Хранит targets, build phases, signing/build settings и ссылки на resources.",
        "why_ru": "Xcode открывает и собирает IPA только через корректный `project.pbxproj`.",
        "responsibilities_ru": "Описать iOS Runner target, resources и build pipeline для IPA.",
        "delete_ru": "Нет — повреждение файла ломает iOS Xcode-проект и IPA build.",
    },
    "macos/Runner.xcodeproj/project.pbxproj": {
        "what_ru": "Главная project database Xcode для macOS Runner. Хранит targets, resources, entitlements, signing и build phases для `.app` bundle.",
        "why_ru": "macOS desktop Counter собирается через этот Xcode-проект в `.app` bundle.",
        "responsibilities_ru": "Описать macOS Runner target и build pipeline для `.app`.",
        "delete_ru": "Нет — без него macOS `.app` не соберётся в Xcode.",
    },
    "windows/runner/resources/app_icon.ico": {
        "what_ru": "ICO-иконка Windows runner. Встраивается в native `.exe` и installer, чтобы Counter имел правильную иконку в taskbar, Explorer и Start menu.",
        "why_ru": "Win32 resource compiler и Inno Setup берут этот ICO для branding установленного app.",
        "responsibilities_ru": "Иконка Counter в taskbar, Explorer, Start menu и setup wizard.",
        "delete_ru": "Нет — `.exe`/installer покажут дефолтную или пустую иконку.",
    },
}
