"""Curated EN+RU descriptions for repository root files."""

from __future__ import annotations

# Each value: what, why, contains, responsibilities, when, delete, connected, layer,
# plus what_ru, why_ru, contains_ru, responsibilities_ru, when_ru, delete_ru, connected_ru, layer_ru

ROOT_FILE_GUIDES: dict[str, dict[str, str]] = {
    ".gitignore": {
        "what": "Git ignore list — tells Git which files and folders must never be committed.",
        "why": "Protects the repo from build output, temp logs, local env secrets, Gradle junk, exports, and IDE cache accidentally landing in git.",
        "contains": "Ignore patterns for `build/`, `.dart_tool/`, `lib/core/env/env.dart`, perf captures, `exports/`, Android `.gradle`.",
        "responsibilities": "Block secrets and generated artifacts from version control.",
        "when": "A new local output folder appears and should stay untracked; accidental `git add` of build files.",
        "delete": "No — repo hygiene and safety.",
        "connected": "All developers, CI, `flutter build` output paths.",
        "layer": "Repo hygiene — not app runtime.",
        "what_ru": "Список того, что Git не должен коммитить: результат сборки, временные логи, локальные env-файлы, Android/Gradle мусор, exports, IDE/cache.",
        "why_ru": "Защищает репозиторий от случайного мусора и секретов в истории git.",
        "contains_ru": "Паттерны для `build/`, `.dart_tool/`, `lib/core/env/env.dart`, perf captures, `exports/`, `.gradle`.",
        "responsibilities_ru": "Не допускать commit build-артефактов и секретов.",
        "when_ru": "Появилась новая локальная папка, которую нельзя коммитить; случайно добавили build в git.",
        "delete_ru": "Нет — гигиена и безопасность репозитория.",
        "connected_ru": "Все разработчики, CI, вывод `flutter build`.",
        "layer_ru": "Гигиена репозитория — не runtime приложения.",
    },
    ".metadata": {
        "what": "Flutter project metadata card — Flutter CLI reads this to know project type and enabled platforms.",
        "why": "Flutter tool uses revision/channel and platform migration data for upgrades and `flutter create` migrations.",
        "contains": "YAML: `project_type: app`, Flutter stable revision, platform list (root, web, android, …).",
        "responsibilities": "Identify this tree as a Flutter app; track migrate-tool platform revisions.",
        "when": "Flutter CLI warns about project version mismatch; after `flutter upgrade` changes project metadata.",
        "delete": "No — unless Flutter safely regenerates it and you verify the diff; normally keep tracked.",
        "connected": "Flutter CLI, `flutter pub get`, platform folders.",
        "layer": "Flutter tooling metadata — not app runtime.",
        "what_ru": "Служебная карточка Flutter-проекта. Flutter CLI использует её, чтобы понимать, что это Flutter app, какие платформы включены и какие project/tooling данные связаны с проектом.",
        "why_ru": "Нужна для `flutter upgrade`, migrate и корректной работы CLI с этим деревом.",
        "contains_ru": "YAML: тип проекта, revision канала stable, список платформ и migrate-метаданные.",
        "responsibilities_ru": "Идентифицировать проект для Flutter CLI.",
        "when_ru": "CLI ругается на версию проекта; после обновления Flutter изменился `.metadata`.",
        "delete_ru": "Нет — удалять только если Flutter пересоздаст файл и diff проверен.",
        "connected_ru": "Flutter CLI, `pubspec.yaml`, platform-папки.",
        "layer_ru": "Метаданные Flutter — не код приложения.",
    },
    "pubspec.yaml": {
        "what": "Main Flutter app manifest — package name, SDK constraints, dependencies, assets, fonts.",
        "why": "Flutter cannot resolve packages or build without this file; every `package:counter/...` import depends on the name here.",
        "contains": "Dependencies (PocketBase SDK, voice, notifications, calendar), asset lists, Flutter plugin config.",
        "responsibilities": "Declare app identity `counter`, version, and all third-party packages.",
        "when": "Adding a Flutter package, bumping app version, registering new assets/fonts.",
        "delete": "No — Flutter cannot build without it.",
        "connected": "`pubspec.lock`, `flutter pub get`, all Dart imports.",
        "layer": "Build manifest — required for every platform build.",
        "what_ru": "Главный паспорт Flutter-приложения: имя package, версии SDK, зависимости, assets, fonts, flutter settings.",
        "why_ru": "Без этого файла Flutter не соберёт приложение и не подтянет пакеты.",
        "contains_ru": "Зависимости (PocketBase, voice, notifications и др.), assets, plugins.",
        "responsibilities_ru": "Объявить package `counter`, версию и все библиотеки.",
        "when_ru": "Добавление пакета, смена версии приложения, новые assets.",
        "delete_ru": "Нет — без него сборка невозможна.",
        "connected_ru": "`pubspec.lock`, `flutter pub get`, все import в Dart.",
        "layer_ru": "Манифест сборки — нужен на всех платформах.",
    },
    "pubspec.lock": {
        "what": "Dependency lockfile — exact resolved versions of every Dart/Flutter package.",
        "why": "Tomorrow's build must use the same library versions as today; prevents surprise breakages from upstream package updates.",
        "contains": "Pinned versions for direct and transitive dependencies after `flutter pub get`.",
        "responsibilities": "Reproducible builds across machines and CI.",
        "when": "After `flutter pub get` changes versions; investigating version-specific bugs.",
        "delete": "No — required for reproducible app builds.",
        "connected": "`pubspec.yaml`, CI, all developer machines.",
        "layer": "Dependency lock — commit to git.",
        "what_ru": "Lock-файл зависимостей. Фиксирует точные версии пакетов, которые реально были resolved.",
        "why_ru": "Чтобы сборка завтра не взяла другие версии библиотек и не получила новый баг.",
        "contains_ru": "Зафиксированные версии прямых и транзитивных зависимостей после `flutter pub get`.",
        "responsibilities_ru": "Одинаковые версии пакетов на всех машинах и в CI.",
        "when_ru": "После изменения зависимостей; расследование бага конкретной версии пакета.",
        "delete_ru": "Нет — нужен для воспроизводимых сборок.",
        "connected_ru": "`pubspec.yaml`, CI, все разработчики.",
        "layer_ru": "Lock зависимостей — коммитится в git.",
    },
    "update.ps1": {
        "what": "Root deploy shortcut — runs the full web publish pipeline via `scripts/manual/td.ps1`.",
        "why": "Owner publishes https://nkuchenov-hash.github.io/Counter/ without memorizing analyze + web build + git push steps.",
        "contains": "Single line: invoke `td.ps1` (checks env, `flutter analyze`, `flutter build web` with base-href `/Counter/`, commit, push → GitHub Actions deploy).",
        "responsibilities": "Documented entry point for GitHub Pages deploy per `docs/DEPLOY.md`.",
        "when": "Publishing website after verified code changes.",
        "delete": "No — documented deploy workflow.",
        "connected": "`.github/workflows/deploy.yml`, `docs/DEPLOY.md`, `web/index.html`.",
        "layer": "Deploy tooling — not app runtime.",
        "what_ru": "Главная команда публикации web-версии. Запускается из root; вызывает `scripts/manual/td.ps1`.",
        "why_ru": "Проверяет env, запускает analyze, собирает Flutter web с `/Counter/`, коммитит изменения и пушит в GitHub — после push GitHub Actions публикует сайт.",
        "contains_ru": "Одна строка вызова `td.ps1` с полным pipeline из `docs/DEPLOY.md`.",
        "responsibilities_ru": "Точка входа для деплоя сайта на GitHub Pages.",
        "when_ru": "Нужно опубликовать сайт после проверенных изменений.",
        "delete_ru": "Нет — задокументированный deploy workflow.",
        "connected_ru": "`.github/workflows/deploy.yml`, `docs/DEPLOY.md`.",
        "layer_ru": "Deploy-скрипт — не runtime приложения.",
    },
    "android.ps1": {
        "what": "Local Android release APK builder — split per CPU ABI with git commit stamp in the app.",
        "why": "Faster than typing long `flutter build apk` commands; injects `GIT_COMMIT` and `BUILD_TIME` for About/build info screen.",
        "contains": "`flutter pub get` → `flutter build apk --release --split-per-abi` with dart-defines; retries with `--no-tree-shake-icons` if icon tree-shake fails; prints APK sizes.",
        "responsibilities": "Produce release APKs under `build/app/outputs/flutter-apk/` (main phone file: `app-arm64-v8a-release.apk`).",
        "when": "Testing release APK on a physical Android device.",
        "delete": "No — documented local Android build path in `docs/APP_STRUCTURE.md`.",
        "connected": "`android/` Gradle project, `lib/core/app_build_info.dart`.",
        "layer": "Build tooling — not app runtime.",
        "what_ru": "Локальная сборка Android release APK — отдельный APK на каждый CPU (split per ABI) со штампом git commit в приложении.",
        "why_ru": "Короче, чем вручную писать `flutter build apk`; подставляет `GIT_COMMIT` и `BUILD_TIME` для экрана About.",
        "contains_ru": "`flutter pub get` → `flutter build apk --release --split-per-abi` с dart-defines; при ошибке icon tree-shake — повтор с `--no-tree-shake-icons`; выводит размеры APK.",
        "responsibilities_ru": "Собрать APK в `build/app/outputs/flutter-apk/` (для современных телефонов: `app-arm64-v8a-release.apk`).",
        "when_ru": "Тест release APK на Android-устройстве.",
        "delete_ru": "Нет — задокументированный путь локальной сборки Android.",
        "connected_ru": "`android/`, `lib/core/app_build_info.dart`.",
        "layer_ru": "Сборка Android — не runtime логика.",
    },
    ".cursorrules": {
        "what": "Cursor IDE rules pointer at repo root — Cursor discovers project rules from this filename.",
        "why": "Cursor reads `.cursorrules` in the project root by convention; this file redirects to the authoritative rules file.",
        "contains": "Short pointer to `.cursor/rules/flutter_expert.mdc` (architecture iron laws, main-thread law).",
        "responsibilities": "Compatibility entry so Cursor agents load real rules from `.cursor/rules/`.",
        "when": "Cursor agent ignores architecture — verify pointer and open `flutter_expert.mdc`.",
        "delete": "No — Cursor root discovery expects this file or equivalent config.",
        "connected": "`.cursor/rules/flutter_expert.mdc`, `docs/ARCHITECTURE.md`.",
        "layer": "IDE agent config — not app runtime.",
        "what_ru": "Указатель правил Cursor в корне репозитория — Cursor ищет project rules именно здесь.",
        "why_ru": "Cursor по convention читает `.cursorrules` в root; файл перенаправляет на полные правила в `.cursor/rules/flutter_expert.mdc`.",
        "contains_ru": "Короткий pointer на iron laws Flutter/PocketBase и main-thread law.",
        "responsibilities_ru": "Совместимость: чтобы агент Cursor подхватил настоящие правила.",
        "when_ru": "Агент Cursor нарушает архитектуру — проверить pointer и открыть `flutter_expert.mdc`.",
        "delete_ru": "Нет — Cursor ожидает rules в root или `.cursor/rules/`.",
        "connected_ru": "`.cursor/rules/flutter_expert.mdc`, `docs/ARCHITECTURE.md`.",
        "layer_ru": "Настройка IDE-агента — не приложение.",
    },
    "AGENT_NAVIGATION.md": {
        "what": "AI navigation map — file→symbol tables, shipped feature status, where to open first in this repo.",
        "why": "Assistants answer ‘where is start/stop record?’ without searching the whole tree; renamed from legacy `CLAUDE.md` filename (no external service dependency).",
        "contains": "Symbol routing tables, local sync map, Iron Laws pointers, governing doc list.",
        "responsibilities": "Orientation doc for AI sessions; update when symbols move.",
        "when": "Finding which file owns a feature; starting an AI coding session.",
        "delete": "No — Project Knowledge pack doc (formerly listed as `CLAUDE.md`).",
        "connected": "`AGENTS.md`, `docs/ARCHITECTURE.md`, `CHANGELOG.md`, 14-doc pack.",
        "layer": "Agent instructions — Project Knowledge.",
        "what_ru": "Карта навигации для AI — таблицы файл→символ, статус фич, куда смотреть первым делом.",
        "why_ru": "Чтобы ассистент быстро находил start/stop record и модули brain; файл переименован из legacy `CLAUDE.md` (не привязан к внешнему сервису).",
        "contains_ru": "Таблицы символов, offline sync, Iron Laws, список governing docs.",
        "responsibilities_ru": "Ориентация для AI; обновлять при переносе символов.",
        "when_ru": "Ищете, в каком файле живёт фича; начало AI-сессии.",
        "delete_ru": "Нет — документ Project Knowledge pack.",
        "connected_ru": "`AGENTS.md`, `docs/ARCHITECTURE.md`, `CHANGELOG.md`.",
        "layer_ru": "Инструкции для AI — Project Knowledge.",
    },
    "AGENTS.md": {
        "what": "Compact root guide for Codex and other AI agents — what to read before editing.",
        "why": "Routes assistants to governing docs and iron laws without duplicating full architecture text.",
        "contains": "Start-here doc list, PocketBase rules summary, structure boundaries, deploy notes.",
        "responsibilities": "First file for Codex; points to `docs/ARCHITECTURE.md` and pack docs.",
        "when": "Starting Codex or generic agent work in this repo.",
        "delete": "No — Project Knowledge pack doc #1.",
        "connected": "`AGENT_NAVIGATION.md`, `docs/APP_STRUCTURE.md`, 14-doc pack.",
        "layer": "Agent instructions — Project Knowledge.",
        "what_ru": "Краткий root-гид для Codex и других AI-агентов — что прочитать перед правками.",
        "why_ru": "Направляет ассистента к governing docs и iron laws без копирования всей архитектуры.",
        "contains_ru": "Список docs «start here», правила PocketBase, границы структуры.",
        "responsibilities_ru": "Первый файл для Codex; ссылки на ARCHITECTURE и pack.",
        "when_ru": "Начало работы Codex/агента в репозитории.",
        "delete_ru": "Нет — документ #1 Project Knowledge pack.",
        "connected_ru": "`AGENT_NAVIGATION.md`, `docs/APP_STRUCTURE.md`.",
        "layer_ru": "Инструкции для AI — Project Knowledge.",
    },
    "CHANGELOG.md": {
        "what": "Development journal — dated list of shipped fixes and structure passes.",
        "why": "Prevents rebuilding features; shows what already landed and when.",
        "contains": "Technical bullets with file names, tagged [shipped]/[wip]/[rollback].",
        "responsibilities": "Record verified work after each session; newest entries on top.",
        "when": "Checking if a bug or feature was already fixed.",
        "delete": "No — Project Knowledge pack history.",
        "connected": "Every structure/deploy report, `docs/ROADMAP.md`.",
        "layer": "History — Project Knowledge.",
        "what_ru": "Журнал разработки — датированный список shipped-изменений и structure passes.",
        "why_ru": "Чтобы не пересобирать уже сделанное; видно, что и когда уже внедрено.",
        "contains_ru": "Технические пункты с именами файлов, теги [shipped]/[wip].",
        "responsibilities_ru": "Фиксировать проверенную работу; новые записи сверху.",
        "when_ru": "Проверка, исправляли ли баг или фичу раньше.",
        "delete_ru": "Нет — история Project Knowledge pack.",
        "connected_ru": "Отчёты structure/deploy, `docs/ROADMAP.md`.",
        "layer_ru": "История — Project Knowledge.",
    },
    "analysis_options.yaml": {
        "what": "Dart analyzer and lint rule configuration for the whole project.",
        "why": "`flutter analyze` and IDE use this to flag errors, warnings, and style issues before merge.",
        "contains": "`include: package:flutter_lints/flutter.yaml` plus project-specific lint toggles.",
        "responsibilities": "Define static analysis policy for CI and local development.",
        "when": "Adding/disabling a lint rule; analyzer behaves differently than expected.",
        "delete": "No — CI and IDE analysis depend on it.",
        "connected": "`flutter analyze`, CI, all Dart files under `lib/` and `test/`.",
        "layer": "Static analysis config — not app runtime.",
        "what_ru": "Настройки Dart analyzer и lint для всего проекта.",
        "why_ru": "`flutter analyze` и IDE читают этот файл, чтобы ловить ошибки и стиль до merge.",
        "contains_ru": "Подключение `flutter_lints` и локальные переключатели правил.",
        "responsibilities_ru": "Политика статического анализа для CI и разработки.",
        "when_ru": "Добавление/отключение lint; analyzer ведёт себя неожиданно.",
        "delete_ru": "Нет — CI и IDE зависят от него.",
        "connected_ru": "`flutter analyze`, CI, `lib/`, `test/`.",
        "layer_ru": "Конфиг analyzer — не runtime.",
    },
    "README.md": {
        "what": "GitHub repository front page — short intro visible to visitors on github.com.",
        "why": "First human-readable page for anyone opening the repo; not part of the 14-doc Project Knowledge law pack.",
        "contains": "Default Flutter starter text (minimal); not the authoritative product spec.",
        "responsibilities": "Orient new visitors; link to Flutter docs.",
        "when": "Updating public repo description on GitHub.",
        "delete": "Maybe — GitHub works without it, but keep for repo presentation.",
        "connected": "GitHub repo home; governing specs live in `docs/`.",
        "layer": "Repo presentation — not app runtime.",
        "what_ru": "Главная страница репозитория на GitHub — короткое описание для посетителей.",
        "why_ru": "Первое, что видит человек на github.com; это не governing spec (она в `docs/`).",
        "contains_ru": "Минимальный starter-текст Flutter.",
        "responsibilities_ru": "Ориентация новых посетителей репозитория.",
        "when_ru": "Обновление публичного описания на GitHub.",
        "delete_ru": "Возможно — GitHub работает и без README, но лучше оставить.",
        "connected_ru": "GitHub; законы проекта — в `docs/`.",
        "layer_ru": "Презентация репо — не приложение.",
    },
    "scripts/manual/capture_notes_glm_main.dart": {
        "what": "Manual Flutter entrypoint that captures Notes GLM editor/library screenshots for parity checks.",
        "why": "Visual Notes regression uses a release Windows run against fixture widgets — not a production app route.",
        "contains": "`main()` that mounts notes GLM parity fixtures from `test/notes/fixtures/`.",
        "responsibilities": "Drive capture UI for `capture_notes_glm_parity.ps1`; no PocketBase writes.",
        "when": "Refreshing Notes GLM golden/capture PNGs after editor/library UI changes.",
        "delete": "No — Notes visual capture workflow depends on this entrypoint.",
        "connected": "`scripts/manual/capture_notes_glm_parity.ps1`, `test/notes/fixtures/`.",
        "layer": "Manual tooling — not production `lib/` UI.",
        "what_ru": "Ручной Flutter entrypoint для capture скриншотов Notes GLM editor/library.",
        "why_ru": "Visual Notes regression гоняет release Windows поверх fixture widgets — не production route.",
        "contains_ru": "`main()` монтирует notes GLM parity fixtures из `test/notes/fixtures/`.",
        "responsibilities_ru": "UI capture для `capture_notes_glm_parity.ps1`; без записи в PocketBase.",
        "when_ru": "Обновление Notes GLM golden/capture PNG после правок editor/library UI.",
        "delete_ru": "Нет — workflow Notes visual capture зависит от этого entrypoint.",
        "connected_ru": "`capture_notes_glm_parity.ps1`, `test/notes/fixtures/`.",
        "layer_ru": "Manual tooling — не production UI в `lib/`.",
    },
    "test/notes/fixtures/notes_glm_parity_fixture.dart": {
        "what": "Widget fixture mounting the Notes GLM editor surface for parity/capture tests.",
        "why": "Moved out of `lib/features/notes/debug/` so test-only capture code is not treated as production UI.",
        "contains": "Flutter widget tree wrapping production Notes editor widgets with mock data.",
        "responsibilities": "Provide stable editor layout for parity tests and manual capture.",
        "when": "Notes editor parity test fails or capture screenshots need refresh.",
        "delete": "No — Notes editor parity/capture imports this fixture.",
        "connected": "`test/notes_glm_editor_parity_test.dart`, `scripts/manual/capture_notes_glm_main.dart`.",
        "layer": "Test fixture — not shipped to users.",
        "what_ru": "Widget fixture с Notes GLM editor surface для parity/capture tests.",
        "why_ru": "Держит test-only Notes capture harness вне production `lib/features/notes/`.",
        "contains_ru": "Flutter widget tree вокруг production Notes editor widgets с mock data.",
        "responsibilities_ru": "Стабильный layout editor для parity tests и manual capture.",
        "when_ru": "Падение Notes editor parity test или refresh capture screenshots.",
        "delete_ru": "Нет — Notes editor parity/capture импортирует этот fixture.",
        "connected_ru": "`notes_glm_editor_parity_test.dart`, `capture_notes_glm_main.dart`.",
        "layer_ru": "Test fixture — не ship пользователю.",
    },
    "test/notes/fixtures/notes_glm_library_parity_fixture.dart": {
        "what": "Widget fixture mounting the Notes GLM library surface for parity/capture tests.",
        "why": "Library grid/list chrome must be captured without living under production `lib/`.",
        "contains": "Flutter widget tree wrapping Notes library/production shell with mock notes.",
        "responsibilities": "Provide stable library layout for parity tests and manual capture.",
        "when": "Notes library parity failures or library capture screenshot updates.",
        "delete": "No — Notes library parity/capture imports this fixture.",
        "connected": "`test/notes_glm_editor_parity_test.dart`, `scripts/manual/capture_notes_glm_main.dart`.",
        "layer": "Test fixture — not shipped to users.",
        "what_ru": "Widget fixture с Notes GLM library surface для parity/capture tests.",
        "why_ru": "Chrome library grid/list нужно capture без размещения под production `lib/`.",
        "contains_ru": "Flutter widget tree вокруг Notes library/production shell с mock notes.",
        "responsibilities_ru": "Стабильный layout library для parity tests и manual capture.",
        "when_ru": "Падения Notes library parity или обновление library capture screenshots.",
        "delete_ru": "Нет — Notes library parity/capture импортирует этот fixture.",
        "connected_ru": "`notes_glm_editor_parity_test.dart`, `capture_notes_glm_main.dart`.",
        "layer_ru": "Test fixture — не ship пользователю.",
    },
    "test/notes/fixtures/notes_production_library_capture.dart": {
        "what": "Production-library capture helper used by the Notes GLM manual capture entrypoint.",
        "why": "Builds the live Lists-tab Notes shell composition for screenshot capture with fixtures.",
        "contains": "Capture-oriented wrappers around `NotesLibraryProductionShell` / related widgets.",
        "responsibilities": "Render production library chrome for Windows capture runs.",
        "when": "Updating production-shell capture frames after Lists Notes UI changes.",
        "delete": "No — manual Notes capture path depends on this helper.",
        "connected": "`scripts/manual/capture_notes_glm_main.dart`, `lib/features/notes/widgets/`.",
        "layer": "Test fixture — not shipped to users.",
        "what_ru": "Helper capture production-library для manual Notes GLM entrypoint.",
        "why_ru": "Собирает composition live Lists-tab Notes shell для screenshot capture с fixtures.",
        "contains_ru": "Capture-oriented wrappers вокруг `NotesLibraryProductionShell` / related widgets.",
        "responsibilities_ru": "Рисует production library chrome для Windows capture runs.",
        "when_ru": "Обновление production-shell capture frames после правок Lists Notes UI.",
        "delete_ru": "Нет — manual Notes capture path зависит от этого helper.",
        "connected_ru": "`capture_notes_glm_main.dart`, `lib/features/notes/widgets/`.",
        "layer_ru": "Test fixture — не ship пользователю.",
    },
}
