const Map<String, String> _peopleEn = <String, String>{
  'title': 'People',
  'subtitle': 'Keep the people you actually want in Life OS. External contacts stay in Sources until you review them.',
  'tab_people': 'People',
  'tab_circles': 'Circles',
  'tab_sources': 'Sources',
  'add_person': 'Add person',
  'edit_person': 'Edit person',
  'add_circle': 'Add circle',
  'edit_circle': 'Edit circle',
  'save': 'Save',
  'cancel': 'Cancel',
  'archive': 'Archive',
  'clear': 'Clear',
  'close': 'Close',
  'refresh': 'Refresh',
  'retry': 'Retry',
  'name': 'Name',
  'phone': 'Phone',
  'email': 'Email',
  'notes': 'Notes',
  'relationship': 'Relationship',
  'status_important': 'Important',
  'status_known': 'Known',
  'status_reference': 'Reference',
  'birthday': 'Birthday',
  'birthday_month': 'Month',
  'birthday_day': 'Day',
  'birthday_year': 'Year (optional)',
  'birthday_notifications': 'Birthday reminders',
  'birthday_notifications_hint': 'Choose when Life OS should remind you.',
  'remind_when': 'Remind me',
  'remind_same_day': 'Same day',
  'remind_days_before': '%s days before',
  'circles': 'Circles',
  'choose_photo': 'Choose photo',
  'remove_photo': 'Remove photo',
  'photo_too_large': 'The photo must be 8 MB or smaller.',
  'photo_failed': 'Could not read that photo.',
  'no_people': 'No People yet',
  'no_people_hint': 'Add someone manually or review a contact in Sources. External contacts never appear here automatically.',
  'no_circles': 'No circles yet',
  'no_circles_hint': 'A person can belong to several circles, for example Family, Close friends, Work or RCC.',
  'circle_name': 'Circle name',
  'people_count': '%s people',
  'source_rule_title': 'Sources are not People',
  'source_rule_body': 'Phone, Google, Microsoft, VK, Telegram and Facebook can contain many irrelevant contacts. Life OS indexes them separately. Only contacts you explicitly add or link become People. Ignored and blocked contacts stay suppressed on future syncs.',
  'source_total': '%s indexed',
  'source_candidates': '%s to review',
  'source_none': 'No contacts indexed',
  'source_device': 'Device contacts',
  'source_google': 'Google Contacts',
  'source_microsoft': 'Microsoft / Outlook',
  'source_vk': 'VK',
  'source_telegram': 'Telegram',
  'source_facebook': 'Facebook',
  'source_ignored': '%s ignored',
  'source_blocked': '%s blocked',
  'source_linked': '%s linked',
  'sync': 'Sync',
  'connect': 'Connect',
  'disconnect': 'Disconnect',
  'connected': 'Connected',
  'not_configured': 'Not configured',
  'server_credentials_needed': 'Provider credentials are not configured on the server.',
  'server_not_deployed': 'People source services are not deployed on the server yet.',
  'mobile_only': 'Mobile only',
  'import_export': 'Import export',
  'telegram_export_hint': 'Import contacts from a Telegram JSON export. Telegram does not provide a normal contacts OAuth flow.',
  'telegram_export_invalid': 'This Telegram export does not contain a readable contacts list.',
  'contacts_permission_denied': 'Contacts permission was not granted.',
  'review': 'Review',
  'reviewing': 'Reviewing',
  'review_hint': 'Nothing below becomes a Person until you choose Add or Link.',
  'show_suppressed': 'Show ignored and blocked',
  'nothing_to_review': 'No contacts in this review view.',
  'add': 'Add',
  'link': 'Link',
  'link_to_person': 'Link to existing Person',
  'ignore': 'Ignore',
  'block': 'Block',
  'restore_to_review': 'Return to review',
  'linked': 'Linked',
  'ignored': 'Ignored',
  'blocked': 'Blocked',
  'unknown': 'Unknown',
  'to_review': 'To review',
  'saved': 'Saved',
  'save_failed': 'Could not save People changes.',
  'load_failed': 'Could not load People.',
  'invalid_birthday': 'Check the birthday date.',
  'required_name': 'Enter a name.',
  'birthday_unknown': 'Birthday not set',
};

const Map<String, String> _peopleRu = <String, String>{
  'title': 'Люди',
  'subtitle': 'Здесь остаются люди, которых вы действительно хотите хранить в Life OS. Внешние контакты остаются в Источниках, пока вы их не проверите.',
  'tab_people': 'Люди',
  'tab_circles': 'Круги',
  'tab_sources': 'Источники',
  'add_person': 'Добавить человека',
  'edit_person': 'Редактировать человека',
  'add_circle': 'Добавить круг',
  'edit_circle': 'Редактировать круг',
  'save': 'Сохранить',
  'cancel': 'Отмена',
  'archive': 'В архив',
  'clear': 'Очистить',
  'close': 'Закрыть',
  'refresh': 'Обновить',
  'retry': 'Повторить',
  'name': 'Имя',
  'phone': 'Телефон',
  'email': 'Email',
  'notes': 'Заметки',
  'relationship': 'Отношение',
  'status_important': 'Важный',
  'status_known': 'Знакомый',
  'status_reference': 'Справочный контакт',
  'birthday': 'День рождения',
  'birthday_month': 'Месяц',
  'birthday_day': 'День',
  'birthday_year': 'Год (необязательно)',
  'birthday_notifications': 'Напоминания о дне рождения',
  'birthday_notifications_hint': 'Выберите, когда Life OS должен напомнить.',
  'remind_when': 'Напомнить',
  'remind_same_day': 'В этот день',
  'remind_days_before': 'За %s дн.',
  'circles': 'Круги',
  'choose_photo': 'Выбрать фото',
  'remove_photo': 'Убрать фото',
  'photo_too_large': 'Фото должно быть не больше 8 МБ.',
  'photo_failed': 'Не удалось прочитать это фото.',
  'no_people': 'Пока нет людей',
  'no_people_hint': 'Добавьте человека вручную или выберите контакт в Источниках. Внешние контакты сюда автоматически не попадают.',
  'no_circles': 'Пока нет кругов',
  'no_circles_hint': 'Один человек может входить сразу в несколько кругов: Семья, Близкие друзья, Работа, RCC и другие.',
  'circle_name': 'Название круга',
  'people_count': 'Людей: %s',
  'source_rule_title': 'Источники — это не Люди',
  'source_rule_body': 'В телефоне, Google, Microsoft, VK, Telegram и Facebook может быть много случайных контактов. Life OS хранит их отдельно. В Люди попадают только те, кого вы явно добавили или связали. Игнорируемые и заблокированные контакты после следующих синхронизаций остаются скрытыми.',
  'source_total': 'В индексе: %s',
  'source_candidates': 'На проверку: %s',
  'source_none': 'Нет контактов в индексе',
  'source_device': 'Контакты устройства',
  'source_google': 'Google Контакты',
  'source_microsoft': 'Microsoft / Outlook',
  'source_vk': 'VK',
  'source_telegram': 'Telegram',
  'source_facebook': 'Facebook',
  'source_ignored': 'Игнорируется: %s',
  'source_blocked': 'Заблокировано: %s',
  'source_linked': 'Связано: %s',
  'sync': 'Синхронизировать',
  'connect': 'Подключить',
  'disconnect': 'Отключить',
  'connected': 'Подключено',
  'not_configured': 'Не настроено',
  'server_credentials_needed': 'На сервере не настроены данные приложения этого провайдера.',
  'server_not_deployed': 'Серверная часть источников People ещё не развёрнута.',
  'mobile_only': 'Только телефон',
  'import_export': 'Импорт экспорта',
  'telegram_export_hint': 'Можно импортировать контакты из JSON-экспорта Telegram. У Telegram нет обычного OAuth-доступа ко всей адресной книге.',
  'telegram_export_invalid': 'В этом экспорте Telegram не найден читаемый список контактов.',
  'contacts_permission_denied': 'Доступ к контактам не предоставлен.',
  'review': 'Проверить',
  'reviewing': 'Открыто',
  'review_hint': 'Ни один контакт ниже не станет Человеком, пока вы не нажмёте Добавить или Связать.',
  'show_suppressed': 'Показывать игнорируемые и заблокированные',
  'nothing_to_review': 'В этом режиме контактов нет.',
  'add': 'Добавить',
  'link': 'Связать',
  'link_to_person': 'Связать с существующим человеком',
  'ignore': 'Игнорировать',
  'block': 'Заблокировать',
  'restore_to_review': 'Вернуть на проверку',
  'linked': 'Связано',
  'ignored': 'Игнорируется',
  'blocked': 'Заблокировано',
  'unknown': 'Не определено',
  'to_review': 'На проверку',
  'saved': 'Сохранено',
  'save_failed': 'Не удалось сохранить изменения.',
  'load_failed': 'Не удалось загрузить Людей.',
  'invalid_birthday': 'Проверьте дату рождения.',
  'required_name': 'Введите имя.',
  'birthday_unknown': 'День рождения не указан',
};

String peopleT(String locale, String key) {
  final source = locale.toLowerCase().startsWith('ru') ? _peopleRu : _peopleEn;
  return source[key] ?? _peopleEn[key] ?? key;
}

String peopleTf(String locale, String key, Object value) =>
    peopleT(locale, key).replaceFirst('%s', '$value');
