const Map<String, String> _peopleEn = <String, String>{
  'title': 'People',
  'subtitle': 'Keep only people who matter. Contact sources stay hidden until you review them.',
  'tab_people': 'People',
  'tab_circles': 'Circles',
  'tab_sources': 'Sources',
  'add_person': 'Add person',
  'edit_person': 'Edit person',
  'add_circle': 'Add circle',
  'save': 'Save',
  'cancel': 'Cancel',
  'archive': 'Archive',
  'name': 'Name',
  'notes': 'Notes',
  'relationship': 'Relationship',
  'status_important': 'Important',
  'status_known': 'Known',
  'status_reference': 'Reference',
  'birthday': 'Birthday',
  'birthday_month': 'Month',
  'birthday_day': 'Day',
  'birthday_year': 'Year (optional)',
  'birthday_notifications': 'Birthday reminders',
  'birthday_notifications_hint': 'Notify 7 days, 1 day and on the birthday.',
  'circles': 'Circles',
  'no_people': 'No tracked people yet.',
  'no_people_hint': 'External contacts do not appear here automatically. Add someone manually or approve a source candidate.',
  'no_circles': 'No circles yet.',
  'no_circles_hint': 'Use circles for Family, Close friends, Work, RCC and other overlapping groups.',
  'circle_name': 'Circle name',
  'source_rule_title': 'Sources are not People',
  'source_rule_body': 'Google, phone, VK, Telegram and other sources may contain thousands of contacts. They stay in a hidden index until you approve them. Ignored and blocked contacts never reappear automatically.',
  'source_total': '%s indexed',
  'source_candidates': '%s to review',
  'source_none': 'No contacts indexed',
  'source_not_connected': 'Not connected',
  'source_device': 'Device contacts',
  'source_google': 'Google Contacts',
  'source_microsoft': 'Microsoft / Outlook',
  'source_vk': 'VK',
  'source_telegram': 'Telegram',
  'source_facebook': 'Facebook',
  'source_ignored': '%s ignored',
  'source_blocked': '%s blocked',
  'source_linked': '%s linked',
  'source_adapter_pending': 'Connector will be configured here; importing never creates visible People without review.',
  'saved': 'Saved',
  'save_failed': 'Could not save People changes.',
  'load_failed': 'Could not load People.',
  'invalid_birthday': 'Check the birthday date.',
  'required_name': 'Enter a name.',
  'birthday_unknown': 'Birthday not set',
};

const Map<String, String> _peopleRu = <String, String>{
  'title': 'Люди',
  'subtitle': 'Здесь остаются только нужные люди. Контакты из источников скрыты, пока вы их не выберете.',
  'tab_people': 'Люди',
  'tab_circles': 'Круги',
  'tab_sources': 'Источники',
  'add_person': 'Добавить человека',
  'edit_person': 'Редактировать',
  'add_circle': 'Добавить круг',
  'save': 'Сохранить',
  'cancel': 'Отмена',
  'archive': 'В архив',
  'name': 'Имя',
  'notes': 'Заметки',
  'relationship': 'Отношение',
  'status_important': 'Важный',
  'status_known': 'Знакомый',
  'status_reference': 'Справочный контакт',
  'birthday': 'День рождения',
  'birthday_month': 'Месяц',
  'birthday_day': 'День',
  'birthday_year': 'Год (необязательно)',
  'birthday_notifications': 'Напоминания о дне рождения',
  'birthday_notifications_hint': 'Напоминать за 7 дней, за 1 день и в сам день.',
  'circles': 'Круги',
  'no_people': 'Пока нет отслеживаемых людей.',
  'no_people_hint': 'Внешние контакты сюда автоматически не попадают. Добавьте человека вручную или подтвердите кандидата из источника.',
  'no_circles': 'Пока нет кругов.',
  'no_circles_hint': 'Круги можно использовать для Семьи, Близких друзей, Работы, RCC и других пересекающихся групп.',
  'circle_name': 'Название круга',
  'source_rule_title': 'Источники — это не Люди',
  'source_rule_body': 'В Google, телефоне, VK, Telegram и других источниках могут быть тысячи контактов. Они хранятся в скрытом индексе, пока вы их не подтвердите. Игнорируемые и заблокированные контакты не появляются снова автоматически.',
  'source_total': 'В индексе: %s',
  'source_candidates': 'На проверку: %s',
  'source_none': 'Нет контактов в индексе',
  'source_not_connected': 'Не подключено',
  'source_device': 'Контакты устройства',
  'source_google': 'Google Контакты',
  'source_microsoft': 'Microsoft / Outlook',
  'source_vk': 'VK',
  'source_telegram': 'Telegram',
  'source_facebook': 'Facebook',
  'source_ignored': 'Игнорируется: %s',
  'source_blocked': 'Заблокировано: %s',
  'source_linked': 'Связано: %s',
  'source_adapter_pending': 'Подключение источника будет настраиваться здесь; импорт никогда не создаёт видимых Людей без проверки.',
  'saved': 'Сохранено',
  'save_failed': 'Не удалось сохранить изменения.',
  'load_failed': 'Не удалось загрузить Людей.',
  'invalid_birthday': 'Проверьте дату рождения.',
  'required_name': 'Введите имя.',
  'birthday_unknown': 'День рождения не указан',
};

String peopleT(String locale, String key) {
  final source = locale.toLowerCase().startsWith('ru') ? _peopleRu : _peopleEn;
  return source[key] ?? _peopleEn[key] ?? key;
}

String peopleTf(String locale, String key, Object value) =>
    peopleT(locale, key).replaceFirst('%s', '$value');
