function env(name) { try { return String($os.getenv(name) || '').trim(); } catch (_) { return ''; } }
function form(values) { var parts=[]; for (var key in values) if (Object.prototype.hasOwnProperty.call(values,key)) parts.push(encodeURIComponent(key)+'='+encodeURIComponent(String(values[key]))); return parts.join('&'); }
function tokenKey(app) { var key=env('SLEEP_SYNC_TOKEN_KEY'); if(key.length===32) return key; var envName=''; try{envName=String(app.encryptionEnv()||'').trim();}catch(_){} var inherited=envName?env(envName):''; if(inherited.length===32) return inherited; throw new Error('token_key_unavailable'); }
function connection(app) { return app.findFirstRecordByFilter('sleep_sync_connections', "provider = 'google_fit'", {}); }
function fitToken(app,c) { var refreshEnc=String(c.get('refresh_token_enc')||''); if(!refreshEnc) throw new Error('refresh_token_missing'); var clientId=env('SLEEP_SYNC_GOOGLE_FIT_CLIENT_ID'), clientSecret=env('SLEEP_SYNC_GOOGLE_FIT_CLIENT_SECRET'); if(!clientId||!clientSecret) throw new Error('oauth_client_missing'); var refresh=String($security.decrypt(refreshEnc,tokenKey(app))); var res=$http.send({url:'https://oauth2.googleapis.com/token',method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form({refresh_token:refresh,client_id:clientId,client_secret:clientSecret,grant_type:'refresh_token',scope:'https://www.googleapis.com/auth/fitness.sleep.read'}),timeout:30}); if(res.statusCode<200||res.statusCode>=300||!res.json||!res.json.access_token) throw new Error('token_refresh_'+res.statusCode); return String(res.json.access_token); }
function clean(v){return String(v||'').replace(/[^a-zA-Z0-9._:\/-]/g,'').slice(0,180);}
function latestDayFromPoints(rows){var latest=0; for(var i=0;i<rows.length;i++){var ns=Number((rows[i]||{}).endTimeNanos||0); var ms=Math.floor(ns/1000000); if(isFinite(ms)&&ms>latest)latest=ms;} return latest?new Date(latest).toISOString().slice(0,10):'none';}
function datasetId(start,end){return String(start.getTime())+'000000-'+String(end.getTime())+'000000';}
function readSource(token,id,start,end){var rows=[],pageToken='',page=0; do{var q={limit:1000}; if(pageToken)q.pageToken=pageToken; var res=$http.send({url:'https://www.googleapis.com/fitness/v1/users/me/dataSources/'+encodeURIComponent(id)+'/datasets/'+datasetId(start,end)+'?'+form(q),method:'GET',headers:{'authorization':'Bearer '+token,'accept':'application/json'},timeout:60}); if(res.statusCode<200||res.statusCode>=300||!res.json)return {status:res.statusCode,count:rows.length,latest:'none'}; var pts=res.json.point||[]; for(var i=0;i<pts.length;i++)rows.push(pts[i]); pageToken=String(res.json.nextPageToken||'').trim(); if(++page>50)break;}while(pageToken); return {status:200,count:rows.length,latest:latestDayFromPoints(rows)};}
function run(e){try{var c=connection(e.app),token=fitToken(e.app,c),start=new Date(Date.now()-4*86400000),end=new Date(); var list=$http.send({url:'https://www.googleapis.com/fitness/v1/users/me/dataSources',method:'GET',headers:{'authorization':'Bearer '+token,'accept':'application/json'},timeout:60}); var rows=(list.json&&list.json.dataSource)||[],out=[]; for(var i=0;i<rows.length;i++){var row=rows[i]||{},dt=row.dataType||{},type=String(dt.name||''),id=String(row.dataStreamId||''); var hay=(type+' '+id+' '+String(row.dataStreamName||'')+' '+String((row.application||{}).packageName||'')+' '+String((row.application||{}).name||'')).toLowerCase(); if(hay.indexOf('sleep')<0)continue; var r=readSource(token,id,start,end); out.push({data_type:clean(type),stream:clean(id),stream_name:clean(row.dataStreamName),app_package:clean((row.application||{}).packageName),app_name:clean((row.application||{}).name),device_manufacturer:clean((row.device||{}).manufacturer),device_model:clean((row.device||{}).model),status:r.status,points_4d:r.count,latest_day:r.latest}); }
var recent=[]; try{recent=e.app.findRecordsByFilter('records',"(title = 'Sleep' || title = 'Сон') && end_time >= {:cutoff}",'',100,0,{cutoff:new Date(Date.now()-36*3600000).toISOString()});}catch(_){} var all=[]; try{all=e.app.findRecordsByFilter('records',"title = 'Sleep' || title = 'Сон'",'',500,0,{});}catch(_){} return e.json(200,{fit_status:list.statusCode,sleep_like_sources:out.length,sources:out,pocketbase_sleep_total:all.length,pocketbase_sleep_last_36h:recent.length,enabled:!!c.get('enabled')});}catch(err){return e.json(200,{diagnostic_error:String(err)});} }
module.exports={run:run};
