import fs from 'node:fs/promises';
import path from 'node:path';
import {XMLParser} from 'fast-xml-parser';

const ROOT=path.resolve('igropoisk'),DATA=path.join(ROOT,'data'),TARGET=140,MAX=240;
const xml=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_'});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const clean=v=>String(v||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).toLowerCase().replace(/[™®©]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const year=v=>Number(String(v||'').match(/(?:19|20)\d{2}/)?.[0]||0);
const to10=(p,n)=>Number(p||0)+Number(n||0)?Math.round(Number(p||0)/(Number(p||0)+Number(n||0))*100)/10:null;
async function req(url,type='json'){const r=await fetch(url,{headers:{'user-agent':'IgropoiskAggregator/1.0','accept':type==='json'?'application/json,*/*':'application/xml,text/xml,*/*'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`${r.status} ${url}`);return type==='json'?r.json():r.text()}
async function spy(name){try{return Object.values(await req(`https://steamspy.com/api.php?request=${name}`)||{})}catch(e){console.warn(name,e.message);return[]}}
const ownerMid=v=>{const a=String(v||'').match(/[\d,]+/g)?.map(x=>Number(x.replace(/,/g,'')))||[];return a.length?a.reduce((x,y)=>x+y,0)/a.length:0};
const seed=g=>Math.log10(ownerMid(g.owners)+1)*20+Math.log10((g.positive||0)+(g.negative||0)+1)*18+Math.log10((g.peakConcurrent||0)+1)*12+(g.discoveryWeight||0)*8;
async function candidates(){const groups=await Promise.all(['top100in2weeks','top100forever','top100owned'].map(spy)),m=new Map();groups.forEach((rows,i)=>rows.forEach(x=>{const id=Number(x.appid);if(!id||!x.name)return;const p=m.get(id)||{},positive=Number(x.positive||p.positive||0),negative=Number(x.negative||p.negative||0);m.set(id,{...p,appid:id,title:x.name,developer:x.developer||p.developer||'',publisher:x.publisher||p.publisher||'',genres:String(x.genre||'').split(',').map(s=>s.trim()).filter(Boolean),tags:Object.keys(x.tags||{}).slice(0,20),positive,negative,steamUserRating:to10(positive,negative),owners:x.owners||p.owners||'',peakConcurrent:Math.max(Number(x.ccu||0),Number(p.peakConcurrent||0)),recommendations:Number(x.recommendations||p.recommendations||0),discoveryWeight:Math.max(Number(p.discoveryWeight||0),3-i),sourceEvidence:['SteamSpy']}))});return[...m.values()].sort((a,b)=>seed(b)-seed(a)).slice(0,MAX)}
async function enrich(g){try{const p=await req(`https://store.steampowered.com/api/appdetails?appids=${g.appid}&l=russian&cc=ru`),d=p?.[g.appid]?.data;if(!d||d.type!=='game')return null;const evidence=['SteamSpy','Steam'];if(d.metacritic?.score)evidence.push('Metacritic');return{...g,id:String(g.appid),title:d.name||g.title,normalizedTitle:norm(d.name||g.title),description:clean(d.short_description),about:clean(d.about_the_game),story:clean(d.short_description),releaseDate:d.release_date?.date||'',year:year(d.release_date?.date),comingSoon:Boolean(d.release_date?.coming_soon),developers:d.developers||[g.developer].filter(Boolean),publishers:d.publishers||[g.publisher].filter(Boolean),genres:d.genres?.map(x=>x.description).filter(Boolean)||g.genres,categories:d.categories?.map(x=>x.description).filter(Boolean)||[],platforms:Object.entries(d.platforms||{}).filter(([,v])=>v).map(([k])=>k),headerImage:d.header_image||'',capsuleImage:`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.appid}/library_600x900.jpg`,heroImage:`https://cdn.cloudflare.steamstatic.com/steam/apps/${g.appid}/library_hero.jpg`,screenshots:(d.screenshots||[]).slice(0,12).map(x=>x.path_full).filter(Boolean),movies:(d.movies||[]).slice(0,3).map(x=>({name:x.name,thumbnail:x.thumbnail,webm:x.webm?.max})).filter(x=>x.webm),criticRating:d.metacritic?.score?Math.round(d.metacritic.score)/10:null,recommendations:Math.max(Number(g.recommendations||0),Number(d.recommendations?.total||0)),sourceEvidence:evidence,sourceLinks:{steam:`https://store.steampowered.com/app/${g.appid}/`,steamSpy:`https://steamspy.com/app/${g.appid}`,metacritic:d.metacritic?.url||''}}}catch(e){console.warn('steam',g.appid,e.message);return null}}
const feeds=[['IGN','en','https://feeds.feedburner.com/ign/all'],['GameSpot','en','https://www.gamespot.com/feeds/mashup/'],['PC Gamer','en','https://www.pcgamer.com/rss/'],['Rock Paper Shotgun','en','https://www.rockpapershotgun.com/feed'],['Eurogamer','en','https://www.eurogamer.net/feed'],['Polygon','en','https://www.polygon.com/rss/index.xml'],['GamesRadar+','en','https://www.gamesradar.com/rss/'],['VG247','en','https://www.vg247.com/feed'],['StopGame','ru','https://rss.stopgame.ru/rss_all.xml'],['Игромания','ru','https://www.igromania.ru/rss/news/']];
const entries=d=>{const a=d?.rss?.channel?.item;if(a)return Array.isArray(a)?a:[a];const b=d?.feed?.entry;return b?(Array.isArray(b)?b:[b]):[]};
async function articles(){const out=[];for(const [source,language,url] of feeds){try{const doc=xml.parse(await req(url,'text'));for(const item of entries(doc).slice(0,150)){const raw=item.link,link=typeof raw==='string'?raw:raw?.['@_href']||item.guid||'',title=clean(item.title);if(!title||!link)continue;out.push({source,language,title,normalizedTitle:norm(title),url:String(link),summary:clean(item.description||item.summary||item['content:encoded']).slice(0,600),publishedAt:item.pubDate||item.published||item.updated||null})}}catch(e){console.warn(source,e.message)}}const m=new Map();out.forEach(x=>m.set(x.url,x));return[...m.values()].sort((a,b)=>new Date(b.publishedAt||0)-new Date(a.publishedAt||0))}
const quality=g=>Boolean(g.appid&&g.title&&g.description?.length>=35&&g.releaseDate&&g.year&&g.developers?.length&&g.publishers?.length&&g.genres?.length&&g.platforms?.length&&g.headerImage&&g.capsuleImage&&g.heroImage&&g.screenshots?.length>=2&&!/soundtrack|demo|dedicated server|test server|benchmark|editor|sdk/i.test(g.title)&&(g.criticRating>=7||g.recommendations>=1000||(g.positive+g.negative)>=5000||ownerMid(g.owners)>=100000));
const popularity=g=>seed(g)+Math.log10((g.recommendations||0)+1)*18+Math.log10((g.positive+g.negative||0)+1)*12+(g.criticRating||0)*6;
function select(games){const sorted=[...games].sort((a,b)=>popularity(b)-popularity(a)),out=[],years=new Map();for(const g of sorted){const cap=g.year>=new Date().getFullYear()-2?18:10;if((years.get(g.year)||0)>=cap)continue;out.push(g);years.set(g.year,(years.get(g.year)||0)+1);if(out.length===TARGET)break}for(const g of sorted){if(out.length===TARGET)break;if(!out.some(x=>x.appid===g.appid))out.push(g)}return out}
function related(g,items){const names=new Set([g.normalizedTitle,...g.title.split(/[:\-–—]/).map(norm)].filter(x=>x.length>=4));return items.filter(a=>[...names].some(n=>a.normalizedTitle.includes(n))).slice(0,40)}
function classify(items){const r={articles:[],reviews:[],guides:[],tips:[],news:[]};for(const x of items){const t=`${x.title} ${x.summary}`.toLowerCase();if(/review|обзор|реценз/.test(t))r.reviews.push(x);else if(/guide|гайд|walkthrough|прохожд/.test(t))r.guides.push(x);else if(/tip|совет|build|билд|best weapon|лучшие/.test(t))r.tips.push(x);else if(/news|анонс|релиз|вышел|update|обновлен|трейлер|дата выхода/.test(t))r.news.push(x);else r.articles.push(x)}return r}
const rating=g=>g.criticRating&&g.steamUserRating?Math.round((g.criticRating*.65+g.steamUserRating*.35)*10)/10:g.criticRating||g.steamUserRating||null;
await fs.mkdir(DATA,{recursive:true});const base=await candidates(),good=[];for(let i=0;i<base.length;i++){const g=await enrich(base[i]);if(g&&quality(g))good.push(g);if((i+1)%20===0)console.log(i+1,good.length);await wait(160)}const allArticles=await articles();const games=select(good).map(g=>{const rel=related(g,allArticles),editorialSources=[...new Set(rel.map(x=>x.source))];return{...g,popularityScore:Math.round(popularity(g)*100)/100,igropoiskRating:rating(g),editorialSources,sourceEvidence:[...new Set([...g.sourceEvidence,...editorialSources])],materials:classify(rel),articles:rel}}).sort((a,b)=>b.popularityScore-a.popularityScore);const now=new Date().toISOString();await fs.writeFile(path.join(DATA,'catalog.json'),JSON.stringify({updatedAt:now,count:games.length,sourcePool:['Steam','SteamSpy','Metacritic',...feeds.map(x=>x[0])],games},null,2));await fs.writeFile(path.join(DATA,'articles.json'),JSON.stringify({updatedAt:now,count:allArticles.length,sources:feeds.map(x=>x[0]),articles:allArticles},null,2));console.log(`saved ${games.length} games, ${allArticles.length} materials`);
